// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";

/**
 * Session describes metadata + content entry for one agent session.
 */
export class Session {
    /**
     * Agent is the agent that produced this session.
     */
    "agent": agents$0.AgentKind;

    /**
     * ID is the session identifier. For JSONL/JSON scanners this is the
     * filename without extension.
     */
    "id": string;

    /**
     * Project is the project path this session belongs to. Derived from
     * the parent directory slug for JSONL scanners; empty for flat JSON
     * and other formats.
     */
    "project"?: string;

    /**
     * StartedAt is the session start time. Currently derived from the
     * file's mtime.
     */
    "started_at": Date;

    /**
     * EndedAt is the session end time. Zero if not derivable.
     */
    "ended_at"?: Date;

    /**
     * MessageCount is the number of message entries in the session.
     */
    "message_count": number;

    /**
     * TokenEstimate is a rough token count (total bytes / 4).
     */
    "token_estimate"?: number;

    /**
     * Path is the on-disk path to the session file.
     */
    "path": string;

    /**
     * Format is the file format identifier: "jsonl", "json", "sqlite".
     */
    "format": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = agents$0.AgentKind.$zero;
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("message_count" in $$source)) {
            this["message_count"] = 0;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField3_0 = $Create.DateFromTime;
        const $$createField4_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("started_at" in $$parsedSource) {
            $$parsedSource["started_at"] = $$createField3_0($$parsedSource["started_at"]);
        }
        if ("ended_at" in $$parsedSource) {
            $$parsedSource["ended_at"] = $$createField4_0($$parsedSource["ended_at"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}
