// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Document is the full tag data persisted to tags.json.
 */
export class Document {
    /**
     * Creates a new Document instance.
     * @param {Partial<Document>} [$$source = {}] - The source object to create the Document.
     */
    constructor($$source = {}) {
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["skills"] = (new State());
        }
        if (!("projects" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["projects"] = (new State());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {GroupEntry[] | undefined}
             */
            this["groups"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Document}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        return new Document(/** @type {Partial<Document>} */($$parsedSource));
    }
}

/**
 * GroupEntry is a named collection of skills.
 */
export class GroupEntry {
    /**
     * Creates a new GroupEntry instance.
     * @param {Partial<GroupEntry>} [$$source = {}] - The source object to create the GroupEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupEntry}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new GroupEntry(/** @type {Partial<GroupEntry>} */($$parsedSource));
    }
}

/**
 * State represents a two-level tag tree (parent -> children).
 * Parents cannot have children; only two levels are supported.
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {Tag[]}
             */
            this["tags"] = [];
        }
        if (!("assigned" in $$source)) {
            /**
             * skillID -> []tagID
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["assigned"] = {};
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField0_0($$parsedSource["tags"]);
        }
        if ("assigned" in $$parsedSource) {
            $$parsedSource["assigned"] = $$createField1_0($$parsedSource["assigned"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

/**
 * Tag represents a single user-assigned label.
 */
export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parentId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = State.createFrom;
const $$createType1 = GroupEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = Tag.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType3);
