// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Document is the full tag data persisted to tags.json.
 */
export class Document {
    "skills": State;
    "projects": State;
    "groups"?: GroupEntry[];

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("skills" in $$source)) {
            this["skills"] = (new State());
        }
        if (!("projects" in $$source)) {
            this["projects"] = (new State());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        if ("groups" in $$parsedSource) {
            $$parsedSource["groups"] = $$createField2_0($$parsedSource["groups"]);
        }
        return new Document($$parsedSource as Partial<Document>);
    }
}

/**
 * GroupEntry is a named collection of skills.
 */
export class GroupEntry {
    "id": string;
    "name": string;
    "skills": string[];

    /** Creates a new GroupEntry instance. */
    constructor($$source: Partial<GroupEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GroupEntry {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new GroupEntry($$parsedSource as Partial<GroupEntry>);
    }
}

/**
 * State represents a two-level tag tree (parent -> children).
 * Parents cannot have children; only two levels are supported.
 */
export class State {
    "tags": Tag[];

    /**
     * skillID -> []tagID
     */
    "assigned": { [_ in string]?: string[] };
    "updatedAt": Date;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("assigned" in $$source)) {
            this["assigned"] = {};
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField0_0($$parsedSource["tags"]);
        }
        if ("assigned" in $$parsedSource) {
            $$parsedSource["assigned"] = $$createField1_0($$parsedSource["assigned"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField2_0($$parsedSource["updatedAt"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * Tag represents a single user-assigned label.
 */
export class Tag {
    "id": string;
    "name": string;
    "parentId"?: string;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

// Private type creation functions
const $$createType0 = State.createFrom;
const $$createType1 = GroupEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = Tag.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType3);
