// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InstallTarget identifies a skill installation directory within a project.
 */
export enum InstallTarget {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TargetShared = "shared",
    TargetClaude = "claude",
    TargetCodex = "codex",
    TargetCursor = "cursor",
    TargetCline = "cline",
    TargetContinue = "continue",
    TargetAider = "aider",
    TargetAntigravity = "antigravity",
    TargetTrae = "trae",
    TargetWindsurf = "windsurf",
};
