// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AgentKind identifies a specific agent runtime.
 * @readonly
 * @enum {string}
 */
export const AgentKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AgentClaude: "claude",
    AgentCodex: "codex",
    AgentCursor: "cursor",
    AgentCline: "cline",
    AgentContinue: "continue",
    AgentAider: "aider",
    AgentAntigravity: "antigravity",
    AgentTrae: "trae",
    AgentWindsurf: "windsurf",
    AgentGeneric: "generic",
};

/**
 * InstallTarget identifies a skill installation directory within a project.
 * @readonly
 * @enum {string}
 */
export const InstallTarget = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TargetShared: "shared",
    TargetClaude: "claude",
    TargetCodex: "codex",
    TargetCursor: "cursor",
    TargetCline: "cline",
    TargetContinue: "continue",
    TargetAider: "aider",
    TargetAntigravity: "antigravity",
    TargetTrae: "trae",
    TargetWindsurf: "windsurf",
};
