// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";

/**
 * ProviderConfig is the common view of an agent's provider configuration.
 * Agent-specific fields that don't fit the common schema go into Extra.
 */
export class ProviderConfig {
    "agent": agents$0.AgentKind;

    /**
     * resolved config file path
     */
    "path": string;

    /**
     * "json", "toml", "yaml", "vscode-settings"
     */
    "format": string;

    /**
     * true if the config file exists on disk
     */
    "exists": boolean;

    /**
     * active provider: "openai", "anthropic", "deepseek", "custom", "unknown"
     */
    "provider": string;

    /**
     * model identifier (e.g. "claude-3.5-sonnet")
     */
    "model": string;

    /**
     * API base URL (empty if using agent default)
     */
    "base_url": string;

    /**
     * masked: "****abcd" (only last 4 chars shown)
     */
    "api_key": string;

    /**
     * all providers found in config (multi-provider agents)
     */
    "providers"?: ProviderEntry[];

    /**
     * agent-specific fields
     */
    "extra": { [_ in string]?: any };

    /**
     * field-level read errors
     */
    "errors": string[];

    /**
     * raw file content (for non-JSON formats)
     */
    "raw": string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = agents$0.AgentKind.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("exists" in $$source)) {
            this["exists"] = false;
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("extra" in $$source)) {
            this["extra"] = {};
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("raw" in $$source)) {
            this["raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField8_0($$parsedSource["providers"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField9_0($$parsedSource["extra"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField10_0($$parsedSource["errors"]);
        }
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

/**
 * ProviderEntry describes one provider entry found in a multi-provider config.
 */
export class ProviderEntry {
    /**
     * provider key (e.g. "ollama", "deepseek")
     */
    "name": string;

    /**
     * default model for this provider
     */
    "model": string;

    /**
     * API base URL
     */
    "base_url": string;

    /**
     * masked API key
     */
    "api_key": string;

    /**
     * true if this is the currently active provider
     */
    "active": boolean;

    /** Creates a new ProviderEntry instance. */
    constructor($$source: Partial<ProviderEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderEntry($$parsedSource as Partial<ProviderEntry>);
    }
}

// Private type creation functions
const $$createType0 = ProviderEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
