// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";

/**
 * MemoryEntry describes a single memory item found during scanning.
 */
export class MemoryEntry {
    /**
     * Agent is the agent that owns this memory entry.
     */
    "agent": agents$0.AgentKind;

    /**
     * Path is the absolute file path of this memory entry.
     */
    "path": string;

    /**
     * Title is a human-readable name for this entry (derived from the file name).
     */
    "title": string;

    /**
     * Kind classifies the entry:
     *   - "index"      for MEMORY.md (the index file)
     *   - "topic"      for topic files linked from MEMORY.md (e.g. topic.md)
     *   - "workspace"  for OpenClaw workspace files (USER.md, AGENTS.md, etc.)
     *   - "daily"      for date-stamped log files (memory/YYYY-MM-DD.md)
     *   - "preference" for preferences.md (Kiro)
     */
    "kind": string;

    /**
     * Content is the full text content of the file.
     */
    "content": string;

    /**
     * SizeBytes is the size of the file in bytes.
     */
    "size_bytes": number;

    /**
     * ModifiedAt is the file's last modification time.
     */
    "modified_at": Date;

    /** Creates a new MemoryEntry instance. */
    constructor($$source: Partial<MemoryEntry> = {}) {
        if (!("agent" in $$source)) {
            this["agent"] = agents$0.AgentKind.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("size_bytes" in $$source)) {
            this["size_bytes"] = 0;
        }
        if (!("modified_at" in $$source)) {
            this["modified_at"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryEntry {
        const $$createField6_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modified_at" in $$parsedSource) {
            $$parsedSource["modified_at"] = $$createField6_0($$parsedSource["modified_at"]);
        }
        return new MemoryEntry($$parsedSource as Partial<MemoryEntry>);
    }
}
