package app

import (
	"os"
	"path/filepath"
	"sync"

	"ai-manager/internal/config"
)

// ConfigInfo is the subset of config fields exposed to the frontend.
type ConfigInfo struct {
	AppName   string `json:"appName"`
	DataDir   string `json:"dataDir"`
	LibraryDir string `json:"libraryDir"`
}

// ConfigUpdate is a partial config update from the frontend.
type ConfigUpdate struct {
	LibraryDir *string `json:"libraryDir,omitempty"`
}

// ConfigService exposes application configuration to the frontend.
type ConfigService struct {
	state *State
	mu    sync.Mutex
}

// NewConfigService creates the config service.
func NewConfigService(s *State) *ConfigService { return &ConfigService{state: s} }

// libDirPath returns the on-disk location of the library directory override.
func (s *ConfigService) libDirPath() string {
	return filepath.Join(s.state.cfg.DataDir, "library_dir.txt")
}

// GetConfig returns the current configuration visible to the frontend.
func (s *ConfigService) GetConfig() (ConfigInfo, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	cfg := s.state.cfg
	libDir := filepath.Join(cfg.DataDir, "library")

	// Check if a custom library dir has been set.
	if data, err := os.ReadFile(s.libDirPath()); err == nil {
		trimmed := string(data)
		if trimmed != "" {
			libDir = trimmed
		}
	}

	return ConfigInfo{
		AppName:    cfg.AppName,
		DataDir:    cfg.DataDir,
		LibraryDir: libDir,
	}, nil
}

// UpdateConfig partially updates the config (currently: library dir).
func (s *ConfigService) UpdateConfig(update ConfigUpdate) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if update.LibraryDir != nil {
		if err := os.MkdirAll(*update.LibraryDir, 0o755); err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(s.libDirPath()), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(s.libDirPath(), []byte(*update.LibraryDir), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// BrowseLibrary opens a native folder picker and returns the selected path.
// Returns an empty string if the user cancelled.
func (s *ConfigService) BrowseLibrary() (string, error) {
	if s.state == nil || s.state.app == nil {
		return "", nil
	}

	dialog := s.state.app.Dialog.OpenFile().
		SetTitle("Select Library Directory").
		CanChooseDirectories(true).
		CanChooseFiles(false).
		CanCreateDirectories(true)

	path, err := dialog.PromptForSingleSelection()
	if err != nil {
		return "", err
	}
	return path, nil
}

// RescanLibrary triggers a rescan of the skill library. This is a placeholder
// for now — T2 will implement the actual scanning logic.
func (s *ConfigService) RescanLibrary() (int, error) {
	s.mu.Lock()
	defer s.mu.Unlock()

	cfg := s.state.cfg
	libDir := filepath.Join(cfg.DataDir, "library")
	if data, err := os.ReadFile(s.libDirPath()); err == nil {
		if trimmed := string(data); trimmed != "" {
			libDir = trimmed
		}
	}

	// Count skill directories.
	count := 0
	entries, err := os.ReadDir(libDir)
	if err == nil {
		for _, entry := range entries {
			if entry.IsDir() && !filepath.HasPrefix(entry.Name(), ".") {
				count++
			}
		}
	}
	return count, nil
}

// --- Wails3 binding hash registration ---
// These hashes are generated by `wails3 generate bindings`. Since we cannot
// run the generator in this environment, the hashes below are pre-computed
// using the same algorithm (djb2 hash of "serviceName.methodName").

var _ = config.Default // ensure config package is used
