// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService exposes agent provider config, session list, and memory
 * views to the frontend via Wails3 bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "../memory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as providers$0 from "../providers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sessions$0 from "../sessions/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAgent returns a single agent's info by kind string.
 */
export function GetAgent(kind: string): $CancellablePromise<$models.AgentInfo | null> {
    return $Call.ByID(2642209090, kind).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetCustomPaths returns all user-configured path overrides.
 */
export function GetCustomPaths(): $CancellablePromise<{ [_ in string]?: $models.CustomAgentPaths }> {
    return $Call.ByID(3578935670).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetMemoryEntry returns a single memory entry's full content.
 */
export function GetMemoryEntry(kind: string, path: string): $CancellablePromise<memory$0.MemoryEntry | null> {
    return $Call.ByID(3632274378, kind, path).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetProviderConfig returns the provider configuration for an agent.
 */
export function GetProviderConfig(kind: string): $CancellablePromise<providers$0.ProviderConfig | null> {
    return $Call.ByID(2766634622, kind).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetSessionTranscript returns the raw transcript content for a session.
 */
export function GetSessionTranscript(kind: string, id: string): $CancellablePromise<string> {
    return $Call.ByID(2806911181, kind, id);
}

/**
 * ListAgents returns all known agents with their paths and capabilities.
 */
export function ListAgents(): $CancellablePromise<$models.AgentInfo[]> {
    return $Call.ByID(3988197309).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListMemory returns memory entries for an agent.
 */
export function ListMemory(kind: string): $CancellablePromise<memory$0.MemoryEntry[]> {
    return $Call.ByID(1696239280, kind).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListSessions returns sessions for an agent, optionally filtered.
 */
export function ListSessions(kind: string, filter: $models.SessionFilter | null): $CancellablePromise<sessions$0.Session[]> {
    return $Call.ByID(577635798, kind, filter).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * OpenMemoryInEditor opens a memory file in the system's default editor.
 */
export function OpenMemoryInEditor(kind: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(848356230, kind, path);
}

/**
 * OpenSessionInEditor opens a session file in the system's default editor.
 */
export function OpenSessionInEditor(kind: string, id: string): $CancellablePromise<void> {
    return $Call.ByID(1178231031, kind, id);
}

/**
 * SaveAgentPaths saves custom path overrides for a single agent.
 */
export function SaveAgentPaths(kind: string, paths: $models.CustomAgentPaths | null): $CancellablePromise<void> {
    return $Call.ByID(2766367617, kind, paths);
}

/**
 * SetEnableUnverifiedPaths toggles scanning of unverified agent paths.
 */
export function SetEnableUnverifiedPaths(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(140921511, enabled);
}

/**
 * UpdateProviderConfig updates the provider configuration for an agent.
 */
export function UpdateProviderConfig(kind: string, patch: providers$0.ProviderConfig | null): $CancellablePromise<providers$0.ProviderConfig | null> {
    return $Call.ByID(609897769, kind, patch).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AgentInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CustomAgentPaths.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = memory$0.MemoryEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = providers$0.ProviderConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType0);
const $$createType9 = $Create.Array($$createType4);
const $$createType10 = sessions$0.Session.createFrom;
const $$createType11 = $Create.Array($$createType10);
