// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutostartService wraps the Wails3 AutostartManager for frontend control
 * of the "launch at login" preference. The actual platform registration
 * (registry on Windows, LaunchAgent on macOS, .desktop on Linux) is
 * handled by the framework.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Disable removes the login registration.
 * @returns {$CancellablePromise<void>}
 */
export function Disable() {
    return $Call.ByID(3389370069);
}

/**
 * Enable registers the app to launch at login.
 * @returns {$CancellablePromise<void>}
 */
export function Enable() {
    return $Call.ByID(2520331612);
}

/**
 * IsEnabled reports whether the app is registered to launch at login.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsEnabled() {
    return $Call.ByID(1102804508);
}

/**
 * SetEnabled is a convenience toggle for the frontend: enable == true calls
 * Enable, false calls Disable.
 * @param {boolean} enable
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(enable) {
    return $Call.ByID(3685221786, enable);
}
