// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService exposes application configuration to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BrowseLibrary opens a native folder picker and returns the selected path.
 * Returns an empty string if the user cancelled.
 */
export function BrowseLibrary(): $CancellablePromise<string> {
    return $Call.ByID(1940905931);
}

/**
 * GetConfig returns the current configuration visible to the frontend.
 */
export function GetConfig(): $CancellablePromise<$models.ConfigInfo> {
    return $Call.ByID(1179290232).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * RescanLibrary triggers a rescan of the skill library. This is a placeholder
 * for now — T2 will implement the actual scanning logic.
 */
export function RescanLibrary(): $CancellablePromise<number> {
    return $Call.ByID(1700331817);
}

/**
 * UpdateConfig partially updates the config (currently: library dir).
 */
export function UpdateConfig(update: $models.ConfigUpdate): $CancellablePromise<void> {
    return $Call.ByID(1782833065, update);
}

// Private type creation functions
const $$createType0 = $models.ConfigInfo.createFrom;
