// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreeterService is a minimal example service showing the Wails3 pattern:
 * 
 *   - NewXService(state) constructor takes the shared *State.
 *   - Every exported method on the struct becomes a method callable from the
 *     frontend (after `wails3 generate bindings`).
 *   - Methods return plain types (or types from this module) that get
 *     marshalled over the JS bridge; multi-return values become the resolve
 *     value + a possible error.
 * 
 * It deliberately does NOT touch config — that's SettingsService's job — so
 * the two services stay orthogonal. Replace / extend this with your own
 * services. Register the service in main.go's application.Services slice.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Greet returns a friendly message for the given name. It demonstrates a
 * simple request/response call from the frontend and emits a "greeting" event
 * the frontend can subscribe to (see State.Emit).
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(3120709457, name);
}

/**
 * Ping is a no-op used to verify the bridge is alive.
 * @returns {$CancellablePromise<string>}
 */
export function Ping() {
    return $Call.ByID(217302952);
}
