// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../skill/models.js";

/**
 * ConfigInfo is the subset of config fields exposed to the frontend.
 */
export class ConfigInfo {
    "appName": string;
    "dataDir": string;
    "libraryDir": string;

    /** Creates a new ConfigInfo instance. */
    constructor($$source: Partial<ConfigInfo> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("libraryDir" in $$source)) {
            this["libraryDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigInfo($$parsedSource as Partial<ConfigInfo>);
    }
}

/**
 * ConfigUpdate is a partial config update from the frontend.
 */
export class ConfigUpdate {
    "libraryDir"?: string | null;

    /** Creates a new ConfigUpdate instance. */
    constructor($$source: Partial<ConfigUpdate> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigUpdate($$parsedSource as Partial<ConfigUpdate>);
    }
}

/**
 * Group is the API-level group representation.
 */
export class Group {
    "id": string;
    "name": string;
    "skills": string[];

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new Group($$parsedSource as Partial<Group>);
    }
}

/**
 * Preferences is the typed shape persisted to disk and exposed to the frontend
 * via the Wails3 bindings. Adding a field here + in DEFAULT_PREFERENCES is the
 * only change needed to introduce a new setting — the frontend gets a typed
 * model automatically after `wails3 generate bindings`.
 */
export class Preferences {
    /**
     * Light/dark/system. "system" follows the OS preference.
     */
    "theme": string;

    /**
     * Id of the active theme (see modules/theme/themes).
     */
    "themeId": string;

    /**
     * UI zoom level, e.g. 1.0 === 100%.
     */
    "zoomLevel": number;

    /**
     * Show dot-prefixed files in the (future) file explorer.
     */
    "showHidden": boolean;

    /**
     * Open automatically at login.
     */
    "launchAtLogin": boolean;

    /**
     * UI language: "en" or "zh".
     */
    "language": string;

    /** Creates a new Preferences instance. */
    constructor($$source: Partial<Preferences> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("themeId" in $$source)) {
            this["themeId"] = "";
        }
        if (!("zoomLevel" in $$source)) {
            this["zoomLevel"] = 0;
        }
        if (!("showHidden" in $$source)) {
            this["showHidden"] = false;
        }
        if (!("launchAtLogin" in $$source)) {
            this["launchAtLogin"] = false;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     */
    static createFrom($$source: any = {}): Preferences {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences($$parsedSource as Partial<Preferences>);
    }
}

/**
 * SearchOptions controls a recursive file search.
 * 
 *   - Root is the directory to start from ("" defaults to the app data dir).
 *   - FileTypes restricts results to the given extensions (e.g. ["go", "ts"]),
 *     matched case-insensitively without the leading dot; empty means all files.
 *   - SkipDirs lists directory names to prune while walking (compared against
 *     the base name, so "node_modules" also skips ".node_modules"). If empty,
 *     a set of common dependency/build/output directories is skipped.
 *   - IncludeHidden, when false, skips dot-prefixed entries (e.g. .git).
 */
export class SearchOptions {
    "root": string;
    "fileTypes": string[];
    "skipDirs": string[];
    "includeHidden": boolean;

    /** Creates a new SearchOptions instance. */
    constructor($$source: Partial<SearchOptions> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("fileTypes" in $$source)) {
            this["fileTypes"] = [];
        }
        if (!("skipDirs" in $$source)) {
            this["skipDirs"] = [];
        }
        if (!("includeHidden" in $$source)) {
            this["includeHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchOptions {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileTypes" in $$parsedSource) {
            $$parsedSource["fileTypes"] = $$createField1_0($$parsedSource["fileTypes"]);
        }
        if ("skipDirs" in $$parsedSource) {
            $$parsedSource["skipDirs"] = $$createField2_0($$parsedSource["skipDirs"]);
        }
        return new SearchOptions($$parsedSource as Partial<SearchOptions>);
    }
}

/**
 * SearchResult is one file (or directory, when Recursive or dirs are kept)
 * found during the walk.
 */
export class SearchResult {
    "path": string;
    "isDir": boolean;
    "size": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SkillDetail is the full detail returned by GetSkill, including the
 * underlying record, file list, and readme content.
 */
export class SkillDetail {
    "record": skill$0.Record;
    "files": string[];
    "readme": string;

    /** Creates a new SkillDetail instance. */
    constructor($$source: Partial<SkillDetail> = {}) {
        if (!("record" in $$source)) {
            this["record"] = (new skill$0.Record());
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("readme" in $$source)) {
            this["readme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillDetail {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new SkillDetail($$parsedSource as Partial<SkillDetail>);
    }
}

/**
 * SkillSummary is a lightweight view of a skill for scan results.
 */
export class SkillSummary {
    "id": string;
    "name": string;
    "slug": string;
    "version": string;
    "origin": string;
    "installed": boolean;

    /** Creates a new SkillSummary instance. */
    constructor($$source: Partial<SkillSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillSummary($$parsedSource as Partial<SkillSummary>);
    }
}

/**
 * UpdateInfo describes a skill update check result.
 */
export class UpdateInfo {
    "name": string;
    "current": string;
    "latest": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = skill$0.Record.createFrom;
