// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../skill/models.js";

/**
 * ConfigInfo is the subset of config fields exposed to the frontend.
 */
export class ConfigInfo {
    /**
     * Creates a new ConfigInfo instance.
     * @param {Partial<ConfigInfo>} [$$source = {}] - The source object to create the ConfigInfo.
     */
    constructor($$source = {}) {
        if (!("appName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["appName"] = "";
        }
        if (!("dataDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataDir"] = "";
        }
        if (!("libraryDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["libraryDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigInfo(/** @type {Partial<ConfigInfo>} */($$parsedSource));
    }
}

/**
 * ConfigUpdate is a partial config update from the frontend.
 */
export class ConfigUpdate {
    /**
     * Creates a new ConfigUpdate instance.
     * @param {Partial<ConfigUpdate>} [$$source = {}] - The source object to create the ConfigUpdate.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["libraryDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigUpdate(/** @type {Partial<ConfigUpdate>} */($$parsedSource));
    }
}

/**
 * Group is the API-level group representation.
 */
export class Group {
    /**
     * Creates a new Group instance.
     * @param {Partial<Group>} [$$source = {}] - The source object to create the Group.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("skills" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Group}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new Group(/** @type {Partial<Group>} */($$parsedSource));
    }
}

/**
 * Preferences is the typed shape persisted to disk and exposed to the frontend
 * via the Wails3 bindings. Adding a field here + in DEFAULT_PREFERENCES is the
 * only change needed to introduce a new setting — the frontend gets a typed
 * model automatically after `wails3 generate bindings`.
 */
export class Preferences {
    /**
     * Creates a new Preferences instance.
     * @param {Partial<Preferences>} [$$source = {}] - The source object to create the Preferences.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * Light/dark/system. "system" follows the OS preference.
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("themeId" in $$source)) {
            /**
             * Id of the active theme (see modules/theme/themes).
             * @member
             * @type {string}
             */
            this["themeId"] = "";
        }
        if (!("zoomLevel" in $$source)) {
            /**
             * UI zoom level, e.g. 1.0 === 100%.
             * @member
             * @type {number}
             */
            this["zoomLevel"] = 0;
        }
        if (!("showHidden" in $$source)) {
            /**
             * Show dot-prefixed files in the (future) file explorer.
             * @member
             * @type {boolean}
             */
            this["showHidden"] = false;
        }
        if (!("launchAtLogin" in $$source)) {
            /**
             * Open automatically at login.
             * @member
             * @type {boolean}
             */
            this["launchAtLogin"] = false;
        }
        if (!("language" in $$source)) {
            /**
             * UI language: "en" or "zh".
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preferences}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences(/** @type {Partial<Preferences>} */($$parsedSource));
    }
}

/**
 * SearchOptions controls a recursive file search.
 * 
 *   - Root is the directory to start from ("" defaults to the app data dir).
 *   - FileTypes restricts results to the given extensions (e.g. ["go", "ts"]),
 *     matched case-insensitively without the leading dot; empty means all files.
 *   - SkipDirs lists directory names to prune while walking (compared against
 *     the base name, so "node_modules" also skips ".node_modules"). If empty,
 *     a set of common dependency/build/output directories is skipped.
 *   - IncludeHidden, when false, skips dot-prefixed entries (e.g. .git).
 */
export class SearchOptions {
    /**
     * Creates a new SearchOptions instance.
     * @param {Partial<SearchOptions>} [$$source = {}] - The source object to create the SearchOptions.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("fileTypes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fileTypes"] = [];
        }
        if (!("skipDirs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skipDirs"] = [];
        }
        if (!("includeHidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["includeHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchOptions}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileTypes" in $$parsedSource) {
            $$parsedSource["fileTypes"] = $$createField1_0($$parsedSource["fileTypes"]);
        }
        if ("skipDirs" in $$parsedSource) {
            $$parsedSource["skipDirs"] = $$createField2_0($$parsedSource["skipDirs"]);
        }
        return new SearchOptions(/** @type {Partial<SearchOptions>} */($$parsedSource));
    }
}

/**
 * SearchResult is one file (or directory, when Recursive or dirs are kept)
 * found during the walk.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * SkillDetail is the full detail returned by GetSkill, including the
 * underlying record, file list, and readme content.
 */
export class SkillDetail {
    /**
     * Creates a new SkillDetail instance.
     * @param {Partial<SkillDetail>} [$$source = {}] - The source object to create the SkillDetail.
     */
    constructor($$source = {}) {
        if (!("record" in $$source)) {
            /**
             * @member
             * @type {skill$0.Record}
             */
            this["record"] = (new skill$0.Record());
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["files"] = [];
        }
        if (!("readme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["readme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new SkillDetail(/** @type {Partial<SkillDetail>} */($$parsedSource));
    }
}

/**
 * SkillSummary is a lightweight view of a skill for scan results.
 */
export class SkillSummary {
    /**
     * Creates a new SkillSummary instance.
     * @param {Partial<SkillSummary>} [$$source = {}] - The source object to create the SkillSummary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("origin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["origin"] = "";
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillSummary(/** @type {Partial<SkillSummary>} */($$parsedSource));
    }
}

/**
 * UpdateInfo describes a skill update check result.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = skill$0.Record.createFrom;
