// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Preferences is the typed shape persisted to disk and exposed to the frontend
 * via the Wails3 bindings. Adding a field here + in DEFAULT_PREFERENCES is the
 * only change needed to introduce a new setting — the frontend gets a typed
 * model automatically after `wails3 generate bindings`.
 */
export class Preferences {
    /**
     * Creates a new Preferences instance.
     * @param {Partial<Preferences>} [$$source = {}] - The source object to create the Preferences.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * Light/dark/system. "system" follows the OS preference.
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("themeId" in $$source)) {
            /**
             * Id of the active theme (see modules/theme/themes).
             * @member
             * @type {string}
             */
            this["themeId"] = "";
        }
        if (!("zoomLevel" in $$source)) {
            /**
             * UI zoom level, e.g. 1.0 === 100%.
             * @member
             * @type {number}
             */
            this["zoomLevel"] = 0;
        }
        if (!("showHidden" in $$source)) {
            /**
             * Show dot-prefixed files in the (future) file explorer.
             * @member
             * @type {boolean}
             */
            this["showHidden"] = false;
        }
        if (!("launchAtLogin" in $$source)) {
            /**
             * Open automatically at login.
             * @member
             * @type {boolean}
             */
            this["launchAtLogin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Preferences}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences(/** @type {Partial<Preferences>} */($$parsedSource));
    }
}

/**
 * SearchOptions controls a recursive file search.
 * 
 *   - Root is the directory to start from ("" defaults to the app data dir).
 *   - FileTypes restricts results to the given extensions (e.g. ["go", "ts"]),
 *     matched case-insensitively without the leading dot; empty means all files.
 *   - SkipDirs lists directory names to prune while walking (compared against
 *     the base name, so "node_modules" also skips ".node_modules"). If empty,
 *     a set of common dependency/build/output directories is skipped.
 *   - IncludeHidden, when false, skips dot-prefixed entries (e.g. .git).
 */
export class SearchOptions {
    /**
     * Creates a new SearchOptions instance.
     * @param {Partial<SearchOptions>} [$$source = {}] - The source object to create the SearchOptions.
     */
    constructor($$source = {}) {
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("fileTypes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fileTypes"] = [];
        }
        if (!("skipDirs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skipDirs"] = [];
        }
        if (!("includeHidden" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["includeHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchOptions}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileTypes" in $$parsedSource) {
            $$parsedSource["fileTypes"] = $$createField1_0($$parsedSource["fileTypes"]);
        }
        if ("skipDirs" in $$parsedSource) {
            $$parsedSource["skipDirs"] = $$createField2_0($$parsedSource["skipDirs"]);
        }
        return new SearchOptions(/** @type {Partial<SearchOptions>} */($$parsedSource));
    }
}

/**
 * SearchResult is one file (or directory, when Recursive or dirs are kept)
 * found during the walk.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
