// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../skill/models.js";

/**
 * AgentInfo is the frontend-facing view of an agent with its paths and
 * capability flags.
 */
export class AgentInfo {
    "kind": agents$0.AgentKind;
    "label": string;
    "icon_type": string;
    "paths": agents$0.AgentPaths;
    "supports_provider": boolean;
    "supports_session": boolean;
    "supports_memory": boolean;
    "status": agents$0.PathStatus;
    "has_provider_config": boolean;
    "has_sessions": boolean;
    "has_memory": boolean;

    /** Creates a new AgentInfo instance. */
    constructor($$source: Partial<AgentInfo> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = agents$0.AgentKind.$zero;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("icon_type" in $$source)) {
            this["icon_type"] = "";
        }
        if (!("paths" in $$source)) {
            this["paths"] = (new agents$0.AgentPaths());
        }
        if (!("supports_provider" in $$source)) {
            this["supports_provider"] = false;
        }
        if (!("supports_session" in $$source)) {
            this["supports_session"] = false;
        }
        if (!("supports_memory" in $$source)) {
            this["supports_memory"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = agents$0.PathStatus.$zero;
        }
        if (!("has_provider_config" in $$source)) {
            this["has_provider_config"] = false;
        }
        if (!("has_sessions" in $$source)) {
            this["has_sessions"] = false;
        }
        if (!("has_memory" in $$source)) {
            this["has_memory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentInfo {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField3_0($$parsedSource["paths"]);
        }
        return new AgentInfo($$parsedSource as Partial<AgentInfo>);
    }
}

/**
 * ConfigInfo is the subset of config fields exposed to the frontend.
 */
export class ConfigInfo {
    "appName": string;
    "dataDir": string;
    "libraryDir": string;

    /** Creates a new ConfigInfo instance. */
    constructor($$source: Partial<ConfigInfo> = {}) {
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("libraryDir" in $$source)) {
            this["libraryDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigInfo($$parsedSource as Partial<ConfigInfo>);
    }
}

/**
 * ConfigUpdate is a partial config update from the frontend.
 */
export class ConfigUpdate {
    "libraryDir"?: string | null;

    /** Creates a new ConfigUpdate instance. */
    constructor($$source: Partial<ConfigUpdate> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigUpdate($$parsedSource as Partial<ConfigUpdate>);
    }
}

/**
 * CustomAgentPaths holds user-configured path overrides for a single agent.
 */
export class CustomAgentPaths {
    "provider_config_path"?: string;
    "session_root_path"?: string;
    "session_format"?: string;
    "memory_root_path"?: string;
    "memory_format"?: string;

    /** Creates a new CustomAgentPaths instance. */
    constructor($$source: Partial<CustomAgentPaths> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomAgentPaths instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomAgentPaths {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomAgentPaths($$parsedSource as Partial<CustomAgentPaths>);
    }
}

/**
 * DiscoverableSkill represents a skill found via search that can be installed.
 */
export class DiscoverableSkill {
    "key": string;
    "name": string;
    "source": string;
    "repoOwner": string;
    "repoName": string;
    "repoBranch": string;
    "installs": number;
    "readmeUrl": string;

    /** Creates a new DiscoverableSkill instance. */
    constructor($$source: Partial<DiscoverableSkill> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("repoOwner" in $$source)) {
            this["repoOwner"] = "";
        }
        if (!("repoName" in $$source)) {
            this["repoName"] = "";
        }
        if (!("repoBranch" in $$source)) {
            this["repoBranch"] = "";
        }
        if (!("installs" in $$source)) {
            this["installs"] = 0;
        }
        if (!("readmeUrl" in $$source)) {
            this["readmeUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoverableSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoverableSkill {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoverableSkill($$parsedSource as Partial<DiscoverableSkill>);
    }
}

/**
 * ExternalSkill represents a skill installed in an agent directory but not
 * managed by the AI-Manager library. It shows which agents have it and
 * allows the user to register it or associate it with other agents.
 */
export class ExternalSkill {
    "name": string;
    "slug": string;
    "description": string;
    "sourceDir": string;
    "canonical": string;

    /**
     * agent key -> true if skill exists in that agent's dir
     */
    "agents": { [_ in string]?: boolean };

    /** Creates a new ExternalSkill instance. */
    constructor($$source: Partial<ExternalSkill> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sourceDir" in $$source)) {
            this["sourceDir"] = "";
        }
        if (!("canonical" in $$source)) {
            this["canonical"] = "";
        }
        if (!("agents" in $$source)) {
            this["agents"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExternalSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): ExternalSkill {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField5_0($$parsedSource["agents"]);
        }
        return new ExternalSkill($$parsedSource as Partial<ExternalSkill>);
    }
}

/**
 * GitHubSearchResult is the result of searching GitHub for skill repositories.
 */
export class GitHubSearchResult {
    "items": {"full_name": string, "html_url": string, "description": string, "stargazers_count": number}[];
    "total_count": number;

    /** Creates a new GitHubSearchResult instance. */
    constructor($$source: Partial<GitHubSearchResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("total_count" in $$source)) {
            this["total_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GitHubSearchResult {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new GitHubSearchResult($$parsedSource as Partial<GitHubSearchResult>);
    }
}

/**
 * Group is the API-level group representation.
 */
export class Group {
    "id": string;
    "name": string;
    "skills": string[];

    /** Creates a new Group instance. */
    constructor($$source: Partial<Group> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Group instance from a string or object.
     */
    static createFrom($$source: any = {}): Group {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField2_0($$parsedSource["skills"]);
        }
        return new Group($$parsedSource as Partial<Group>);
    }
}

/**
 * Preferences is the typed shape persisted to disk and exposed to the frontend
 * via the Wails3 bindings. Adding a field here + in DEFAULT_PREFERENCES is the
 * only change needed to introduce a new setting — the frontend gets a typed
 * model automatically after `wails3 generate bindings`.
 */
export class Preferences {
    /**
     * Light/dark/system. "system" follows the OS preference.
     */
    "theme": string;

    /**
     * Id of the active theme (see modules/theme/themes).
     */
    "themeId": string;

    /**
     * UI zoom level, e.g. 1.0 === 100%.
     */
    "zoomLevel": number;

    /**
     * Show dot-prefixed files in the (future) file explorer.
     */
    "showHidden": boolean;

    /**
     * Open automatically at login.
     */
    "launchAtLogin": boolean;

    /**
     * UI language: "en" or "zh".
     */
    "language": string;

    /** Creates a new Preferences instance. */
    constructor($$source: Partial<Preferences> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("themeId" in $$source)) {
            this["themeId"] = "";
        }
        if (!("zoomLevel" in $$source)) {
            this["zoomLevel"] = 0;
        }
        if (!("showHidden" in $$source)) {
            this["showHidden"] = false;
        }
        if (!("launchAtLogin" in $$source)) {
            this["launchAtLogin"] = false;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Preferences instance from a string or object.
     */
    static createFrom($$source: any = {}): Preferences {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Preferences($$parsedSource as Partial<Preferences>);
    }
}

/**
 * SearchOptions controls a recursive file search.
 * 
 *   - Root is the directory to start from ("" defaults to the app data dir).
 *   - FileTypes restricts results to the given extensions (e.g. ["go", "ts"]),
 *     matched case-insensitively without the leading dot; empty means all files.
 *   - SkipDirs lists directory names to prune while walking (compared against
 *     the base name, so "node_modules" also skips ".node_modules"). If empty,
 *     a set of common dependency/build/output directories is skipped.
 *   - IncludeHidden, when false, skips dot-prefixed entries (e.g. .git).
 */
export class SearchOptions {
    "root": string;
    "fileTypes": string[];
    "skipDirs": string[];
    "includeHidden": boolean;

    /** Creates a new SearchOptions instance. */
    constructor($$source: Partial<SearchOptions> = {}) {
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("fileTypes" in $$source)) {
            this["fileTypes"] = [];
        }
        if (!("skipDirs" in $$source)) {
            this["skipDirs"] = [];
        }
        if (!("includeHidden" in $$source)) {
            this["includeHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchOptions {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileTypes" in $$parsedSource) {
            $$parsedSource["fileTypes"] = $$createField1_0($$parsedSource["fileTypes"]);
        }
        if ("skipDirs" in $$parsedSource) {
            $$parsedSource["skipDirs"] = $$createField2_0($$parsedSource["skipDirs"]);
        }
        return new SearchOptions($$parsedSource as Partial<SearchOptions>);
    }
}

/**
 * SearchResult is one file (or directory, when Recursive or dirs are kept)
 * found during the walk.
 */
export class SearchResult {
    "path": string;
    "isDir": boolean;
    "size": number;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * SessionFilter filters sessions by project and/or time.
 */
export class SessionFilter {
    "project": string;

    /**
     * ISO 8601 timestamp (empty = no filter)
     */
    "since": string;

    /**
     * default 50
     */
    "limit": number;

    /** Creates a new SessionFilter instance. */
    constructor($$source: Partial<SessionFilter> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("since" in $$source)) {
            this["since"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFilter($$parsedSource as Partial<SessionFilter>);
    }
}

/**
 * SkillAgentStatus represents a Library skill with its agent installation status.
 */
export class SkillAgentStatus {
    "name": string;
    "slug": string;
    "version": string;
    "description": string;
    "sourceDir": string;

    /**
     * "local", "github", "skills.sh"
     */
    "origin": string;

    /**
     * true if a newer version is available
     */
    "hasUpdate": boolean;

    /**
     * agent key -> installed (symlink exists)
     */
    "agents": { [_ in string]?: boolean };

    /** Creates a new SkillAgentStatus instance. */
    constructor($$source: Partial<SkillAgentStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sourceDir" in $$source)) {
            this["sourceDir"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }
        if (!("agents" in $$source)) {
            this["agents"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillAgentStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillAgentStatus {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField7_0($$parsedSource["agents"]);
        }
        return new SkillAgentStatus($$parsedSource as Partial<SkillAgentStatus>);
    }
}

/**
 * SkillDetail is the full detail returned by GetSkill, including the
 * underlying record, file list, and readme content.
 */
export class SkillDetail {
    "record": skill$0.Record;
    "files": string[];
    "readme": string;

    /** Creates a new SkillDetail instance. */
    constructor($$source: Partial<SkillDetail> = {}) {
        if (!("record" in $$source)) {
            this["record"] = (new skill$0.Record());
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("readme" in $$source)) {
            this["readme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillDetail {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new SkillDetail($$parsedSource as Partial<SkillDetail>);
    }
}

/**
 * SkillSummary is a lightweight view of a skill for scan results.
 */
export class SkillSummary {
    "id": string;
    "name": string;
    "slug": string;
    "version": string;
    "origin": string;
    "installed": boolean;

    /** Creates a new SkillSummary instance. */
    constructor($$source: Partial<SkillSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillSummary($$parsedSource as Partial<SkillSummary>);
    }
}

/**
 * SkillsShSearchResult is the result of searching skills.sh.
 */
export class SkillsShSearchResult {
    "skills": DiscoverableSkill[];
    "totalCount": number;
    "query": string;

    /** Creates a new SkillsShSearchResult instance. */
    constructor($$source: Partial<SkillsShSearchResult> = {}) {
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillsShSearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillsShSearchResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        return new SkillsShSearchResult($$parsedSource as Partial<SkillsShSearchResult>);
    }
}

/**
 * UpdateInfo describes a skill update check result.
 */
export class UpdateInfo {
    "name": string;
    "current": string;
    "latest": string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = agents$0.AgentPaths.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = skill$0.Record.createFrom;
const $$createType5 = DiscoverableSkill.createFrom;
const $$createType6 = $Create.Array($$createType5);
