// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService manages projects, skill installations, and effective skill
 * calculation. It is exposed to the frontend via Wails3 bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as effective$0 from "../effective/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../project/models.js";

/**
 * AddProject registers a project directory.
 */
export function AddProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(3984554427, path);
}

/**
 * BrowseProject opens a folder picker dialog and returns the selected path.
 * Uses the Wails v3 Dialog API to let the user choose a directory.
 */
export function BrowseProject(): $CancellablePromise<string> {
    return $Call.ByID(2255002878);
}

/**
 * EnsureProjectsFileExists creates an empty projects.json if it doesn't exist.
 * This ensures the frontend always has a valid file to read.
 */
export function EnsureProjectsFileExists(): $CancellablePromise<void> {
    return $Call.ByID(1202599633);
}

/**
 * GetEffectiveSkills returns all skills visible in a project, deduplicated
 * across agents by canonical (resolved symlink) path. Mirrors Kitter:
 * scans all agent directories, resolves symlinks, deduplicates by source.
 */
export function GetEffectiveSkills(projectPath: string): $CancellablePromise<effective$0.EffectiveSkill[]> {
    return $Call.ByID(4293750628, projectPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * InstallSkills installs multiple skills into a project's target directories.
 * If global is true, installs into shared target only; otherwise installs into
 * all specified targets.
 */
export function InstallSkills(names: string[], projectPath: string, targets: agents$0.InstallTarget[], global: boolean): $CancellablePromise<void> {
    return $Call.ByID(4192481716, names, projectPath, targets, global);
}

/**
 * ListInstallations returns all skill installations in a project.
 */
export function ListInstallations(projectPath: string): $CancellablePromise<project$0.Installation[]> {
    return $Call.ByID(22827492, projectPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListProjects returns all registered projects.
 */
export function ListProjects(): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(3774475349).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RemoveProject removes a project by path.
 */
export function RemoveProject(path: string): $CancellablePromise<void> {
    return $Call.ByID(2920833648, path);
}

/**
 * UninstallSkill removes a skill from a specific target in a project.
 */
export function UninstallSkill(projectPath: string, name: string, target: agents$0.InstallTarget): $CancellablePromise<void> {
    return $Call.ByID(2170377360, projectPath, name, target);
}

// Private type creation functions
const $$createType0 = effective$0.EffectiveSkill.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = project$0.Installation.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = project$0.Project.createFrom;
const $$createType5 = $Create.Array($$createType4);
