// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SearchService walks a directory tree and returns matching files. It lets the
 * caller scope a search to a specific directory, restrict results to certain
 * file types, and prune directories (like node_modules) that shouldn't be
 * scanned. This is the backend half of the file-explorer / search feature.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Search walks Root (recursively), returning every file that passes the
 * FileTypes filter while skipping any directory whose base name is in the
 * effective skip set. It returns paths relative to Root.
 * @param {$models.SearchOptions} opts
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function Search(opts) {
    return $Call.ByID(2204932292, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SearchResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
