// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService persists the frontend's preferences as a single JSON file on
 * disk. The frontend keeps the authoritative settings object (theme mode,
 * theme id, zoom level, …) in a zustand store and calls SavePrefs whenever it
 * changes (debounced), then LoadPrefs on startup. The backend is just dumb
 * JSON persistence — no domain knowledge — so adding a new setting never
 * requires touching Go beyond the Preferences struct above.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadPrefs returns the saved preferences, falling back to defaults if the
 * file does not exist yet.
 * @returns {$CancellablePromise<$models.Preferences>}
 */
export function LoadPrefs() {
    return $Call.ByID(210428201).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SavePrefs atomically writes the preferences to disk.
 * @param {$models.Preferences} prefs
 * @returns {$CancellablePromise<void>}
 */
export function SavePrefs(prefs) {
    return $Call.ByID(2402405374, prefs);
}

// Private type creation functions
const $$createType0 = $models.Preferences.createFrom;
