// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService manages the skill library through the Wails3 binding layer.
 * It exposes 6 methods that the frontend calls to list, add, remove, and
 * check updates for skills.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../skill/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddSkill adds a skill to the library from one of 4 source types.
 * The kind parameter determines which scanner to use:
 *   - "local": input is a directory path to scan for skill directories
 *   - "npx": input is an npx/skills.sh/GitHub package name
 *   - "claude": input is a Claude plugin name
 *   - "existing": input is a comma-separated list of existing install paths
 */
export function AddSkill(kind: string, input: string, groupName: string): $CancellablePromise<void> {
    return $Call.ByID(2329671467, kind, input, groupName);
}

/**
 * CheckUpdates checks all skills in the library for available updates.
 * For local skills, the version from metadata.json is compared against
 * itself (no remote check). For remote skills, this would check the
 * source for newer versions.
 * Currently returns empty list since remote update checking is not
 * implemented yet — each skill's current version is reported as latest.
 */
export function CheckUpdates(): $CancellablePromise<$models.UpdateInfo[]> {
    return $Call.ByID(1988037945).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSkill returns the full detail (record + files + readme) for a skill
 * identified by name or slug.
 */
export function GetSkill(name: string): $CancellablePromise<$models.SkillDetail> {
    return $Call.ByID(2501105826, name).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListSkills returns all skills in the library as Summaries.
 */
export function ListSkills(): $CancellablePromise<skill$0.Summary[]> {
    return $Call.ByID(3187451021).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * RemoveSkill removes a skill from the library by name or slug.
 */
export function RemoveSkill(name: string): $CancellablePromise<void> {
    return $Call.ByID(4259806480, name);
}

/**
 * UpdateSkill updates a skill to its latest version.
 * Currently a no-op since remote update resolution is not implemented.
 */
export function UpdateSkill(name: string): $CancellablePromise<void> {
    return $Call.ByID(2125119895, name);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SkillDetail.createFrom;
const $$createType3 = skill$0.Summary.createFrom;
const $$createType4 = $Create.Array($$createType3);
