// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService manages the skill library through the Wails3 binding layer.
 * It exposes 6 methods that the frontend calls to list, add, remove, and
 * check updates for skills.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skill$0 from "../skill/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddSkill adds selected skills to the library. The selectedSlugs parameter
 * contains the slugs of skills to add (from a prior ScanSkill call). If empty,
 * all scanned skills are added.
 * @param {string} kind
 * @param {string} input
 * @param {string} groupName
 * @param {string[]} selectedSlugs
 * @returns {$CancellablePromise<void>}
 */
export function AddSkill(kind, input, groupName, selectedSlugs) {
    return $Call.ByID(2329671467, kind, input, groupName, selectedSlugs);
}

/**
 * CheckUpdates checks all skills in the library for available updates.
 * For local skills, the version from metadata.json is compared against
 * itself (no remote check). For remote skills, this would check the
 * source for newer versions.
 * Currently returns empty list since remote update checking is not
 * implemented yet — each skill's current version is reported as latest.
 * @returns {$CancellablePromise<$models.UpdateInfo[]>}
 */
export function CheckUpdates() {
    return $Call.ByID(1988037945).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSkill returns the full detail (record + files + readme) for a skill
 * identified by name or slug.
 * @param {string} name
 * @returns {$CancellablePromise<$models.SkillDetail>}
 */
export function GetSkill(name) {
    return $Call.ByID(2501105826, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListSkills returns all skills in the library as Summaries.
 * @returns {$CancellablePromise<skill$0.Summary[]>}
 */
export function ListSkills() {
    return $Call.ByID(3187451021).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RemoveSkill removes a skill from the library by name or slug.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveSkill(name) {
    return $Call.ByID(4259806480, name);
}

/**
 * ScanSkill scans a source without adding anything. Returns the list of
 * discovered skills for preview. The frontend shows these in a result list
 * with multi-select, then calls AddSkill with the selected slugs.
 * @param {string} kind
 * @param {string} input
 * @returns {$CancellablePromise<$models.SkillSummary[]>}
 */
export function ScanSkill(kind, input) {
    return $Call.ByID(4292178559, kind, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * UpdateSkill updates a skill to its latest version.
 * Currently a no-op since remote update resolution is not implemented.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSkill(name) {
    return $Call.ByID(2125119895, name);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SkillDetail.createFrom;
const $$createType3 = skill$0.Summary.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SkillSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
