// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TagGroupService manages tags and groups, persisted to tags.json.
 * Deep module: 9 methods at the interface, full tag tree + persistence behind it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tags$0 from "../tags/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddGroup creates a new group.
 */
export function AddGroup(name: string): $CancellablePromise<$models.Group | null> {
    return $Call.ByID(3807643685, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddTag adds a tag to the document. If parentID is non-empty, it's a child tag.
 * Returns the new tag.
 */
export function AddTag(name: string, parentID: string): $CancellablePromise<tags$0.Tag | null> {
    return $Call.ByID(477410730, name, parentID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * AssignTag assigns a tag to a skill.
 */
export function AssignTag(skillID: string, tagID: string): $CancellablePromise<void> {
    return $Call.ByID(3100758398, skillID, tagID);
}

/**
 * DeleteGroup removes a group by ID. Skills are moved to Ungrouped.
 */
export function DeleteGroup(groupID: string): $CancellablePromise<void> {
    return $Call.ByID(168186759, groupID);
}

/**
 * DeleteTag removes a tag by ID and unassigns it from all skills.
 */
export function DeleteTag(tagID: string): $CancellablePromise<void> {
    return $Call.ByID(72157436, tagID);
}

/**
 * ListGroups returns all groups.
 */
export function ListGroups(): $CancellablePromise<$models.Group[]> {
    return $Call.ByID(3644079007).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListTags returns the full tags document (skills tags + projects tags).
 */
export function ListTags(): $CancellablePromise<tags$0.Document | null> {
    return $Call.ByID(3255532386).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * MoveSkillToGroup adds a skill to a group (removes from other groups first).
 */
export function MoveSkillToGroup(skillID: string, groupID: string): $CancellablePromise<void> {
    return $Call.ByID(3815050981, skillID, groupID);
}

/**
 * RenameTag renames a tag by ID.
 */
export function RenameTag(tagID: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(2835269627, tagID, newName);
}

/**
 * UnassignTag removes a tag assignment from a skill.
 */
export function UnassignTag(skillID: string, tagID: string): $CancellablePromise<void> {
    return $Call.ByID(3815637183, skillID, tagID);
}

// Private type creation functions
const $$createType0 = $models.Group.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = tags$0.Tag.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = tags$0.Document.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
