// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TagGroupService manages tags and groups, persisted to tags.json.
 * Deep module: 9 methods at the interface, full tag tree + persistence behind it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tags$0 from "../tags/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddGroup creates a new group.
 * @param {string} name
 * @returns {$CancellablePromise<$models.Group | null>}
 */
export function AddGroup(name) {
    return $Call.ByID(3807643685, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * AddTag adds a tag to the document. If parentID is non-empty, it's a child tag.
 * Returns the new tag.
 * @param {string} name
 * @param {string} parentID
 * @returns {$CancellablePromise<tags$0.Tag | null>}
 */
export function AddTag(name, parentID) {
    return $Call.ByID(477410730, name, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * AssignTag assigns a tag to a skill.
 * @param {string} skillID
 * @param {string} tagID
 * @returns {$CancellablePromise<void>}
 */
export function AssignTag(skillID, tagID) {
    return $Call.ByID(3100758398, skillID, tagID);
}

/**
 * DeleteGroup removes a group by ID. Skills are moved to Ungrouped.
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(groupID) {
    return $Call.ByID(168186759, groupID);
}

/**
 * DeleteTag removes a tag by ID and unassigns it from all skills.
 * @param {string} tagID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTag(tagID) {
    return $Call.ByID(72157436, tagID);
}

/**
 * ListGroups returns all groups.
 * @returns {$CancellablePromise<$models.Group[]>}
 */
export function ListGroups() {
    return $Call.ByID(3644079007).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListTags returns the full tags document (skills tags + projects tags).
 * @returns {$CancellablePromise<tags$0.Document | null>}
 */
export function ListTags() {
    return $Call.ByID(3255532386).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * MoveSkillToGroup adds a skill to a group (removes from other groups first).
 * @param {string} skillID
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function MoveSkillToGroup(skillID, groupID) {
    return $Call.ByID(3815050981, skillID, groupID);
}

/**
 * RenameTag renames a tag by ID.
 * @param {string} tagID
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTag(tagID, newName) {
    return $Call.ByID(2835269627, tagID, newName);
}

/**
 * UnassignTag removes a tag assignment from a skill.
 * @param {string} skillID
 * @param {string} tagID
 * @returns {$CancellablePromise<void>}
 */
export function UnassignTag(skillID, tagID) {
    return $Call.ByID(3815637183, skillID, tagID);
}

// Private type creation functions
const $$createType0 = $models.Group.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = tags$0.Tag.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = tags$0.Document.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
