// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService wraps the Wails3 updater for frontend consumption.
 * The frontend calls CheckForUpdates / DownloadAndInstall / Restart; the
 * updater's own events (EventUpdateAvailable, EventUpdateReady, …) are
 * emitted on the app's event bus and can be subscribed to directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "../../../github.com/wailsapp/wails/v3/pkg/updater/models.js";

/**
 * CheckAndInstall opens the built-in update window and runs the full flow
 * (check → download → verify → stage). The user dismisses the window.
 * @returns {$CancellablePromise<void>}
 */
export function CheckAndInstall() {
    return $Call.ByID(3063614667);
}

/**
 * CheckForUpdates queries the GitHub releases endpoint for a newer version.
 * Returns nil if already up to date.
 * @returns {$CancellablePromise<updater$0.Release | null>}
 */
export function CheckForUpdates() {
    return $Call.ByID(2031374016).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CurrentVersion returns the version string the updater was configured with.
 * @returns {$CancellablePromise<string>}
 */
export function CurrentVersion() {
    return $Call.ByID(632166110);
}

/**
 * Restart quits the app and swaps in the staged update. Only valid after a
 * successful DownloadAndInstall.
 * @returns {$CancellablePromise<void>}
 */
export function Restart() {
    return $Call.ByID(3445570068);
}

/**
 * UpdateState reports the updater's current lifecycle phase as a string,
 * so the frontend can render the right UI without importing the enum.
 * @returns {$CancellablePromise<string>}
 */
export function UpdateState() {
    return $Call.ByID(2298233777);
}

// Private type creation functions
const $$createType0 = updater$0.Release.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
