// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EffectiveSkill represents one deduplicated skill across all agents.
 */
export class EffectiveSkill {
    "name": string;
    "description": string;

    /**
     * symlink back to library
     */
    "managed": boolean;
    "builtin": boolean;

    /**
     * agent kinds that see this skill
     */
    "agents": string[];

    /**
     * symlink paths (agent-specific dirs)
     */
    "locations": string[];

    /**
     * resolved real source path
     */
    "canonicalPath": string;
    "tokens": number;
    "warning": boolean;
    "danger": boolean;

    /**
     * number of agents that see this skill
     */
    "skillCount": number;

    /** Creates a new EffectiveSkill instance. */
    constructor($$source: Partial<EffectiveSkill> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("managed" in $$source)) {
            this["managed"] = false;
        }
        if (!("builtin" in $$source)) {
            this["builtin"] = false;
        }
        if (!("agents" in $$source)) {
            this["agents"] = [];
        }
        if (!("locations" in $$source)) {
            this["locations"] = [];
        }
        if (!("canonicalPath" in $$source)) {
            this["canonicalPath"] = "";
        }
        if (!("tokens" in $$source)) {
            this["tokens"] = 0;
        }
        if (!("warning" in $$source)) {
            this["warning"] = false;
        }
        if (!("danger" in $$source)) {
            this["danger"] = false;
        }
        if (!("skillCount" in $$source)) {
            this["skillCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EffectiveSkill instance from a string or object.
     */
    static createFrom($$source: any = {}): EffectiveSkill {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField4_0($$parsedSource["agents"]);
        }
        if ("locations" in $$parsedSource) {
            $$parsedSource["locations"] = $$createField5_0($$parsedSource["locations"]);
        }
        return new EffectiveSkill($$parsedSource as Partial<EffectiveSkill>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
