// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EffectiveSkill represents a skill as an agent would see it.
 */
export class EffectiveSkill {
    /**
     * Creates a new EffectiveSkill instance.
     * @param {Partial<EffectiveSkill>} [$$source = {}] - The source object to create the EffectiveSkill.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "managed", "unmanaged", "builtin"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("managed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["managed"] = false;
        }
        if (!("tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tokens"] = 0;
        }
        if (!("warning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["warning"] = false;
        }
        if (!("danger" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["danger"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EffectiveSkill instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EffectiveSkill}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EffectiveSkill(/** @type {Partial<EffectiveSkill>} */($$parsedSource));
    }
}
