// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Origin describes where a skill came from.
 */
export class Origin {
    "type": OriginType;
    "path"?: string;
    "repo"?: string;
    "subdir"?: string;

    /** Creates a new Origin instance. */
    constructor($$source: Partial<Origin> = {}) {
        if (!("type" in $$source)) {
            this["type"] = OriginType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Origin instance from a string or object.
     */
    static createFrom($$source: any = {}): Origin {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Origin($$parsedSource as Partial<Origin>);
    }
}

/**
 * OriginType identifies where a skill was sourced from.
 */
export enum OriginType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OriginLocal = "local",
    OriginGitHub = "github",
    OriginSkillsSh = "skills.sh",
    OriginClaude = "claude",
    OriginBuiltin = "builtin",
    OriginUnknown = "unknown",
};

/**
 * Record is the full metadata for a single skill in the library.
 */
export class Record {
    "id": string;
    "name": string;
    "slug": string;
    "version": string;
    "description"?: string;
    "authors"?: string[];
    "license"?: string;
    "keywords"?: string[];
    "tags"?: string[];
    "group"?: string;
    "origin": Origin;
    "installed": boolean;
    "updatedAt": Date;
    "installedAt"?: Date;

    /** Creates a new Record instance. */
    constructor($$source: Partial<Record> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("origin" in $$source)) {
            this["origin"] = (new Origin());
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     */
    static createFrom($$source: any = {}): Record {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField12_0 = $Create.DateFromTime;
        const $$createField13_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authors" in $$parsedSource) {
            $$parsedSource["authors"] = $$createField5_0($$parsedSource["authors"]);
        }
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField7_0($$parsedSource["keywords"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField8_0($$parsedSource["tags"]);
        }
        if ("origin" in $$parsedSource) {
            $$parsedSource["origin"] = $$createField10_0($$parsedSource["origin"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField12_0($$parsedSource["updatedAt"]);
        }
        if ("installedAt" in $$parsedSource) {
            $$parsedSource["installedAt"] = $$createField13_0($$parsedSource["installedAt"]);
        }
        return new Record($$parsedSource as Partial<Record>);
    }
}

/**
 * Summary is a lightweight representation of a skill for list views.
 */
export class Summary {
    "id": string;
    "name": string;
    "slug": string;
    "version": string;
    "description"?: string;
    "installed": boolean;
    "updatedAt": Date;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("installed" in $$source)) {
            this["installed"] = false;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField6_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField6_0($$parsedSource["updatedAt"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = Origin.createFrom;
