// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";

/**
 * Installation represents a skill installation (symlink) in a project.
 */
export class Installation {
    /**
     * Creates a new Installation instance.
     * @param {Partial<Installation>} [$$source = {}] - The source object to create the Installation.
     */
    constructor($$source = {}) {
        if (!("skillName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["skillName"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {agents$0.InstallTarget}
             */
            this["target"] = agents$0.InstallTarget.$zero;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isSymlink" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isSymlink"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Installation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Installation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Installation(/** @type {Partial<Installation>} */($$parsedSource));
    }
}

/**
 * Project represents a registered project directory.
 */
export class Project {
    /**
     * Creates a new Project instance.
     * @param {Partial<Project>} [$$source = {}] - The source object to create the Project.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Project}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project(/** @type {Partial<Project>} */($$parsedSource));
    }
}
