// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agents$0 from "../agents/models.js";

/**
 * Installation represents a skill installation (symlink) in a project.
 */
export class Installation {
    "skillName": string;
    "target": agents$0.InstallTarget;
    "path": string;
    "isSymlink": boolean;

    /** Creates a new Installation instance. */
    constructor($$source: Partial<Installation> = {}) {
        if (!("skillName" in $$source)) {
            this["skillName"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = agents$0.InstallTarget.$zero;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isSymlink" in $$source)) {
            this["isSymlink"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Installation instance from a string or object.
     */
    static createFrom($$source: any = {}): Installation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Installation($$parsedSource as Partial<Installation>);
    }
}

/**
 * Project represents a registered project directory.
 */
export class Project {
    "path": string;
    "name": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}
