import type { Theme } from "./types";
import { DEFAULT_THEME_ID } from "./types";

/**
 * 15 built-in themes. Each provides light and dark variants with the full
 * CSS-variable palette (background, foreground, primary, accent, sidebar, …).
 *
 * Theme IDs are stable — they are persisted in preferences.json and survive
 * app upgrades. Adding a new theme = append to this array.
 */
export const BUILTIN_THEMES: Theme[] = [
  // --- Default ---
  {
    id: "claude",
    name: "Claude",
    description: "Warm parchment with clay accents",
    variants: {
      light: {
        colors: {
          background: "#faf9f5",
          foreground: "#1a1915",
          card: "#ffffff",
          cardForeground: "#1a1915",
          popover: "#ffffff",
          popoverForeground: "#1a1915",
          primary: "#c96442",
          primaryForeground: "#ffffff",
          secondary: "#f0eee6",
          secondaryForeground: "#5c5a52",
          muted: "#f0eee6",
          mutedForeground: "#8b8980",
          accent: "#f5e6d8",
          accentForeground: "#8b4513",
          destructive: "#d93025",
          border: "#e0ddd4",
          input: "#e0ddd4",
          ring: "#c96442",
          sidebar: "#f5f3eb",
          sidebarForeground: "#1a1915",
          sidebarPrimary: "#c96442",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#f5e6d8",
          sidebarAccentForeground: "#8b4513",
          sidebarBorder: "#e0ddd4",
          sidebarRing: "#c96442",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#1a1915",
          foreground: "#f5f3eb",
          card: "#252318",
          cardForeground: "#f5f3eb",
          popover: "#252318",
          popoverForeground: "#f5f3eb",
          primary: "#e08a5e",
          primaryForeground: "#1a1915",
          secondary: "#2d2b1e",
          secondaryForeground: "#a8a598",
          muted: "#2d2b1e",
          mutedForeground: "#8b8980",
          accent: "#3d2e1e",
          accentForeground: "#f5e6d8",
          destructive: "#ff6b6b",
          border: "#3d3b2e",
          input: "#3d3b2e",
          ring: "#e08a5e",
          sidebar: "#1e1c14",
          sidebarForeground: "#f5f3eb",
          sidebarPrimary: "#e08a5e",
          sidebarPrimaryForeground: "#1a1915",
          sidebarAccent: "#3d2e1e",
          sidebarAccentForeground: "#f5e6d8",
          sidebarBorder: "#3d3b2e",
          sidebarRing: "#e08a5e",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Cool / Blue ---
  {
    id: "sky",
    name: "Sky",
    description: "Clean light blues and whites",
    variants: {
      light: {
        colors: {
          background: "#f8fafc",
          foreground: "#0f172a",
          card: "#ffffff",
          cardForeground: "#0f172a",
          popover: "#ffffff",
          popoverForeground: "#0f172a",
          primary: "#0284c7",
          primaryForeground: "#ffffff",
          secondary: "#e2e8f0",
          secondaryForeground: "#475569",
          muted: "#e2e8f0",
          mutedForeground: "#64748b",
          accent: "#e0f2fe",
          accentForeground: "#0c4a6e",
          destructive: "#dc2626",
          border: "#cbd5e1",
          input: "#cbd5e1",
          ring: "#0284c7",
          sidebar: "#f1f5f9",
          sidebarForeground: "#0f172a",
          sidebarPrimary: "#0284c7",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#e0f2fe",
          sidebarAccentForeground: "#0c4a6e",
          sidebarBorder: "#cbd5e1",
          sidebarRing: "#0284c7",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#0f172a",
          foreground: "#f1f5f9",
          card: "#1e293b",
          cardForeground: "#f1f5f9",
          popover: "#1e293b",
          popoverForeground: "#f1f5f9",
          primary: "#38bdf8",
          primaryForeground: "#0f172a",
          secondary: "#334155",
          secondaryForeground: "#94a3b8",
          muted: "#334155",
          mutedForeground: "#64748b",
          accent: "#164e63",
          accentForeground: "#e0f2fe",
          destructive: "#f87171",
          border: "#334155",
          input: "#334155",
          ring: "#38bdf8",
          sidebar: "#162032",
          sidebarForeground: "#f1f5f9",
          sidebarPrimary: "#38bdf8",
          sidebarPrimaryForeground: "#0f172a",
          sidebarAccent: "#164e63",
          sidebarAccentForeground: "#e0f2fe",
          sidebarBorder: "#334155",
          sidebarRing: "#38bdf8",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Purple ---
  {
    id: "violet",
    name: "Violet",
    description: "Deep purples with lavender accents",
    variants: {
      light: {
        colors: {
          background: "#faf5ff",
          foreground: "#1e1b2e",
          card: "#ffffff",
          cardForeground: "#1e1b2e",
          popover: "#ffffff",
          popoverForeground: "#1e1b2e",
          primary: "#7c3aed",
          primaryForeground: "#ffffff",
          secondary: "#ede9fe",
          secondaryForeground: "#5b21b6",
          muted: "#ede9fe",
          mutedForeground: "#7c7488",
          accent: "#f3e8ff",
          accentForeground: "#5b21b6",
          destructive: "#dc2626",
          border: "#ddd6fe",
          input: "#ddd6fe",
          ring: "#7c3aed",
          sidebar: "#f5f0ff",
          sidebarForeground: "#1e1b2e",
          sidebarPrimary: "#7c3aed",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#f3e8ff",
          sidebarAccentForeground: "#5b21b6",
          sidebarBorder: "#ddd6fe",
          sidebarRing: "#7c3aed",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#1e1b2e",
          foreground: "#f5f0ff",
          card: "#2d2840",
          cardForeground: "#f5f0ff",
          popover: "#2d2840",
          popoverForeground: "#f5f0ff",
          primary: "#a78bfa",
          primaryForeground: "#1e1b2e",
          secondary: "#3b3358",
          secondaryForeground: "#b8a8d4",
          muted: "#3b3358",
          mutedForeground: "#7c7488",
          accent: "#4c1d95",
          accentForeground: "#f3e8ff",
          destructive: "#f87171",
          border: "#4c4070",
          input: "#4c4070",
          ring: "#a78bfa",
          sidebar: "#231f33",
          sidebarForeground: "#f5f0ff",
          sidebarPrimary: "#a78bfa",
          sidebarPrimaryForeground: "#1e1b2e",
          sidebarAccent: "#4c1d95",
          sidebarAccentForeground: "#f3e8ff",
          sidebarBorder: "#4c4070",
          sidebarRing: "#a78bfa",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Green ---
  {
    id: "forest",
    name: "Forest",
    description: "Deep greens with mossy tones",
    variants: {
      light: {
        colors: {
          background: "#f7fef7",
          foreground: "#0f2418",
          card: "#ffffff",
          cardForeground: "#0f2418",
          popover: "#ffffff",
          popoverForeground: "#0f2418",
          primary: "#16a34a",
          primaryForeground: "#ffffff",
          secondary: "#dcfce7",
          secondaryForeground: "#166534",
          muted: "#dcfce7",
          mutedForeground: "#5e8a6c",
          accent: "#d1fae5",
          accentForeground: "#166534",
          destructive: "#dc2626",
          border: "#bbf7d0",
          input: "#bbf7d0",
          ring: "#16a34a",
          sidebar: "#f0fdf4",
          sidebarForeground: "#0f2418",
          sidebarPrimary: "#16a34a",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#d1fae5",
          sidebarAccentForeground: "#166534",
          sidebarBorder: "#bbf7d0",
          sidebarRing: "#16a34a",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#0f2418",
          foreground: "#f0fdf4",
          card: "#1a3325",
          cardForeground: "#f0fdf4",
          popover: "#1a3325",
          popoverForeground: "#f0fdf4",
          primary: "#4ade80",
          primaryForeground: "#0f2418",
          secondary: "#234030",
          secondaryForeground: "#8fbfa0",
          muted: "#234030",
          mutedForeground: "#5e8a6c",
          accent: "#14532d",
          accentForeground: "#d1fae5",
          destructive: "#f87171",
          border: "#2d5a3d",
          input: "#2d5a3d",
          ring: "#4ade80",
          sidebar: "#14271c",
          sidebarForeground: "#f0fdf4",
          sidebarPrimary: "#4ade80",
          sidebarPrimaryForeground: "#0f2418",
          sidebarAccent: "#14532d",
          sidebarAccentForeground: "#d1fae5",
          sidebarBorder: "#2d5a3d",
          sidebarRing: "#4ade80",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Ocean ---
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep teal and cyan palette",
    variants: {
      light: {
        colors: {
          background: "#f0fdfa",
          foreground: "#042f2e",
          card: "#ffffff",
          cardForeground: "#042f2e",
          popover: "#ffffff",
          popoverForeground: "#042f2e",
          primary: "#0d9488",
          primaryForeground: "#ffffff",
          secondary: "#ccfbf1",
          secondaryForeground: "#115e59",
          muted: "#ccfbf1",
          mutedForeground: "#5e8a86",
          accent: "#99f6e4",
          accentForeground: "#115e59",
          destructive: "#dc2626",
          border: "#99f6e4",
          input: "#99f6e4",
          ring: "#0d9488",
          sidebar: "#ecfdf5",
          sidebarForeground: "#042f2e",
          sidebarPrimary: "#0d9488",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#99f6e4",
          sidebarAccentForeground: "#115e59",
          sidebarBorder: "#99f6e4",
          sidebarRing: "#0d9488",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#042f2e",
          foreground: "#ecfdf5",
          card: "#0a3d3b",
          cardForeground: "#ecfdf5",
          popover: "#0a3d3b",
          popoverForeground: "#ecfdf5",
          primary: "#2dd4bf",
          primaryForeground: "#042f2e",
          secondary: "#134e4a",
          secondaryForeground: "#8fbfb8",
          muted: "#134e4a",
          mutedForeground: "#5e8a86",
          accent: "#115e59",
          accentForeground: "#99f6e4",
          destructive: "#f87171",
          border: "#1d6b66",
          input: "#1d6b66",
          ring: "#2dd4bf",
          sidebar: "#062926",
          sidebarForeground: "#ecfdf5",
          sidebarPrimary: "#2dd4bf",
          sidebarPrimaryForeground: "#042f2e",
          sidebarAccent: "#115e59",
          sidebarAccentForeground: "#99f6e4",
          sidebarBorder: "#1d6b66",
          sidebarRing: "#2dd4bf",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Sunset ---
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm oranges and pinks",
    variants: {
      light: {
        colors: {
          background: "#fff7ed",
          foreground: "#1c1917",
          card: "#ffffff",
          cardForeground: "#1c1917",
          popover: "#ffffff",
          popoverForeground: "#1c1917",
          primary: "#ea580c",
          primaryForeground: "#ffffff",
          secondary: "#ffedd5",
          secondaryForeground: "#9a3412",
          muted: "#ffedd5",
          mutedForeground: "#8b7355",
          accent: "#fed7aa",
          accentForeground: "#9a3412",
          destructive: "#dc2626",
          border: "#fdba74",
          input: "#fdba74",
          ring: "#ea580c",
          sidebar: "#fffbeb",
          sidebarForeground: "#1c1917",
          sidebarPrimary: "#ea580c",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#fed7aa",
          sidebarAccentForeground: "#9a3412",
          sidebarBorder: "#fdba74",
          sidebarRing: "#ea580c",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#1c1917",
          foreground: "#fff7ed",
          card: "#292524",
          cardForeground: "#fff7ed",
          popover: "#292524",
          popoverForeground: "#fff7ed",
          primary: "#fb923c",
          primaryForeground: "#1c1917",
          secondary: "#44403c",
          secondaryForeground: "#d4c4b0",
          muted: "#44403c",
          mutedForeground: "#8b7355",
          accent: "#7c2d12",
          accentForeground: "#fed7aa",
          destructive: "#f87171",
          border: "#57534e",
          input: "#57534e",
          ring: "#fb923c",
          sidebar: "#1a1714",
          sidebarForeground: "#fff7ed",
          sidebarPrimary: "#fb923c",
          sidebarPrimaryForeground: "#1c1917",
          sidebarAccent: "#7c2d12",
          sidebarAccentForeground: "#fed7aa",
          sidebarBorder: "#57534e",
          sidebarRing: "#fb923c",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Rose ---
  {
    id: "rose",
    name: "Rose",
    description: "Soft pinks and deep rose tones",
    variants: {
      light: {
        colors: {
          background: "#fff1f2",
          foreground: "#1c1917",
          card: "#ffffff",
          cardForeground: "#1c1917",
          popover: "#ffffff",
          popoverForeground: "#1c1917",
          primary: "#e11d48",
          primaryForeground: "#ffffff",
          secondary: "#ffe4e6",
          secondaryForeground: "#9f1239",
          muted: "#ffe4e6",
          mutedForeground: "#8b7378",
          accent: "#fecdd3",
          accentForeground: "#9f1239",
          destructive: "#dc2626",
          border: "#fecdd3",
          input: "#fecdd3",
          ring: "#e11d48",
          sidebar: "#fff5f6",
          sidebarForeground: "#1c1917",
          sidebarPrimary: "#e11d48",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#fecdd3",
          sidebarAccentForeground: "#9f1239",
          sidebarBorder: "#fecdd3",
          sidebarRing: "#e11d48",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#1c1917",
          foreground: "#fff1f2",
          card: "#292524",
          cardForeground: "#fff1f2",
          popover: "#292524",
          popoverForeground: "#fff1f2",
          primary: "#fb7185",
          primaryForeground: "#1c1917",
          secondary: "#44403c",
          secondaryForeground: "#d4b0b8",
          muted: "#44403c",
          mutedForeground: "#8b7378",
          accent: "#881337",
          accentForeground: "#fecdd3",
          destructive: "#f87171",
          border: "#57534e",
          input: "#57534e",
          ring: "#fb7185",
          sidebar: "#1a1714",
          sidebarForeground: "#fff1f2",
          sidebarPrimary: "#fb7185",
          sidebarPrimaryForeground: "#1c1917",
          sidebarAccent: "#881337",
          sidebarAccentForeground: "#fecdd3",
          sidebarBorder: "#57534e",
          sidebarRing: "#fb7185",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Nord ---
  {
    id: "nord",
    name: "Nord",
    description: "Nordic dark palette (nord theme)",
    variants: {
      light: {
        colors: {
          background: "#eceff4",
          foreground: "#2e3440",
          card: "#ffffff",
          cardForeground: "#2e3440",
          popover: "#ffffff",
          popoverForeground: "#2e3440",
          primary: "#5e81ac",
          primaryForeground: "#ffffff",
          secondary: "#d8dee9",
          secondaryForeground: "#4c566a",
          muted: "#d8dee9",
          mutedForeground: "#616e88",
          accent: "#d8dee9",
          accentForeground: "#4c566a",
          destructive: "#bf616a",
          border: "#d8dee9",
          input: "#d8dee9",
          ring: "#5e81ac",
          sidebar: "#e5e9f0",
          sidebarForeground: "#2e3440",
          sidebarPrimary: "#5e81ac",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#d8dee9",
          sidebarAccentForeground: "#4c566a",
          sidebarBorder: "#d8dee9",
          sidebarRing: "#5e81ac",
          radius: "0.375rem",
        },
      },
      dark: {
        colors: {
          background: "#2e3440",
          foreground: "#eceff4",
          card: "#3b4252",
          cardForeground: "#eceff4",
          popover: "#3b4252",
          popoverForeground: "#eceff4",
          primary: "#88c0d0",
          primaryForeground: "#2e3440",
          secondary: "#434c5e",
          secondaryForeground: "#d8dee9",
          muted: "#434c5e",
          mutedForeground: "#81a1c1",
          accent: "#4c566a",
          accentForeground: "#d8dee9",
          destructive: "#bf616a",
          border: "#434c5e",
          input: "#434c5e",
          ring: "#88c0d0",
          sidebar: "#282c34",
          sidebarForeground: "#eceff4",
          sidebarPrimary: "#88c0d0",
          sidebarPrimaryForeground: "#2e3440",
          sidebarAccent: "#4c566a",
          sidebarAccentForeground: "#d8dee9",
          sidebarBorder: "#434c5e",
          sidebarRing: "#88c0d0",
          radius: "0.375rem",
        },
      },
    },
  },
  // --- Dracula ---
  {
    id: "dracula",
    name: "Dracula",
    description: "Dark purple with pastel accents",
    variants: {
      light: {
        colors: {
          background: "#f5f5f5",
          foreground: "#282a36",
          card: "#ffffff",
          cardForeground: "#282a36",
          popover: "#ffffff",
          popoverForeground: "#282a36",
          primary: "#bd93f9",
          primaryForeground: "#282a36",
          secondary: "#e2e2e2",
          secondaryForeground: "#6272a4",
          muted: "#e2e2e2",
          mutedForeground: "#6272a4",
          accent: "#e2e2e2",
          accentForeground: "#6272a4",
          destructive: "#ff5555",
          border: "#e2e2e2",
          input: "#e2e2e2",
          ring: "#bd93f9",
          sidebar: "#f0f0f0",
          sidebarForeground: "#282a36",
          sidebarPrimary: "#bd93f9",
          sidebarPrimaryForeground: "#282a36",
          sidebarAccent: "#e2e2e2",
          sidebarAccentForeground: "#6272a4",
          sidebarBorder: "#e2e2e2",
          sidebarRing: "#bd93f9",
          radius: "0.375rem",
        },
      },
      dark: {
        colors: {
          background: "#282a36",
          foreground: "#f8f8f2",
          card: "#44475a",
          cardForeground: "#f8f8f2",
          popover: "#44475a",
          popoverForeground: "#f8f8f2",
          primary: "#bd93f9",
          primaryForeground: "#282a36",
          secondary: "#44475a",
          secondaryForeground: "#f8f8f2",
          muted: "#44475a",
          mutedForeground: "#6272a4",
          accent: "#6272a4",
          accentForeground: "#f8f8f2",
          destructive: "#ff5555",
          border: "#44475a",
          input: "#44475a",
          ring: "#bd93f9",
          sidebar: "#21222c",
          sidebarForeground: "#f8f8f2",
          sidebarPrimary: "#bd93f9",
          sidebarPrimaryForeground: "#282a36",
          sidebarAccent: "#6272a4",
          sidebarAccentForeground: "#f8f8f2",
          sidebarBorder: "#44475a",
          sidebarRing: "#bd93f9",
          radius: "0.375rem",
        },
      },
    },
  },
  // --- Monokai ---
  {
    id: "monokai",
    name: "Monokai",
    description: "Classic editor dark theme",
    variants: {
      light: {
        colors: {
          background: "#f5f5f5",
          foreground: "#272822",
          card: "#ffffff",
          cardForeground: "#272822",
          popover: "#ffffff",
          popoverForeground: "#272822",
          primary: "#a6e22e",
          primaryForeground: "#272822",
          secondary: "#e6e6e6",
          secondaryForeground: "#75715e",
          muted: "#e6e6e6",
          mutedForeground: "#75715e",
          accent: "#e6e6e6",
          accentForeground: "#75715e",
          destructive: "#f92672",
          border: "#e6e6e6",
          input: "#e6e6e6",
          ring: "#a6e22e",
          sidebar: "#f0f0f0",
          sidebarForeground: "#272822",
          sidebarPrimary: "#a6e22e",
          sidebarPrimaryForeground: "#272822",
          sidebarAccent: "#e6e6e6",
          sidebarAccentForeground: "#75715e",
          sidebarBorder: "#e6e6e6",
          sidebarRing: "#a6e22e",
          radius: "0.25rem",
        },
      },
      dark: {
        colors: {
          background: "#272822",
          foreground: "#f8f8f2",
          card: "#3e3d32",
          cardForeground: "#f8f8f2",
          popover: "#3e3d32",
          popoverForeground: "#f8f8f2",
          primary: "#a6e22e",
          primaryForeground: "#272822",
          secondary: "#3e3d32",
          secondaryForeground: "#f8f8f2",
          muted: "#3e3d32",
          mutedForeground: "#75715e",
          accent: "#75715e",
          accentForeground: "#f8f8f2",
          destructive: "#f92672",
          border: "#3e3d32",
          input: "#3e3d32",
          ring: "#a6e22e",
          sidebar: "#1e1f1a",
          sidebarForeground: "#f8f8f2",
          sidebarPrimary: "#a6e22e",
          sidebarPrimaryForeground: "#272822",
          sidebarAccent: "#75715e",
          sidebarAccentForeground: "#f8f8f2",
          sidebarBorder: "#3e3d32",
          sidebarRing: "#a6e22e",
          radius: "0.25rem",
        },
      },
    },
  },
  // --- Gruvbox ---
  {
    id: "gruvbox",
    name: "Gruvbox",
    description: "Muted retro colors",
    variants: {
      light: {
        colors: {
          background: "#fbf1c7",
          foreground: "#3c3836",
          card: "#f2e7b8",
          cardForeground: "#3c3836",
          popover: "#f2e7b8",
          popoverForeground: "#3c3836",
          primary: "#af3ac0",
          primaryForeground: "#fbf1c7",
          secondary: "#ebdbb2",
          secondaryForeground: "#665c54",
          muted: "#ebdbb2",
          mutedForeground: "#7c6f64",
          accent: "#ebdbb2",
          accentForeground: "#665c54",
          destructive: "#cc241d",
          border: "#d5c4a1",
          input: "#d5c4a1",
          ring: "#af3ac0",
          sidebar: "#f2e7b8",
          sidebarForeground: "#3c3836",
          sidebarPrimary: "#af3ac0",
          sidebarPrimaryForeground: "#fbf1c7",
          sidebarAccent: "#ebdbb2",
          sidebarAccentForeground: "#665c54",
          sidebarBorder: "#d5c4a1",
          sidebarRing: "#af3ac0",
          radius: "0.25rem",
        },
      },
      dark: {
        colors: {
          background: "#282828",
          foreground: "#ebdbb2",
          card: "#3c3836",
          cardForeground: "#ebdbb2",
          popover: "#3c3836",
          popoverForeground: "#ebdbb2",
          primary: "#d3869b",
          primaryForeground: "#282828",
          secondary: "#504945",
          secondaryForeground: "#d5c4a1",
          muted: "#504945",
          mutedForeground: "#a89984",
          accent: "#504945",
          accentForeground: "#d5c4a1",
          destructive: "#fb4934",
          border: "#504945",
          input: "#504945",
          ring: "#d3869b",
          sidebar: "#1d2021",
          sidebarForeground: "#ebdbb2",
          sidebarPrimary: "#d3869b",
          sidebarPrimaryForeground: "#282828",
          sidebarAccent: "#504945",
          sidebarAccentForeground: "#d5c4a1",
          sidebarBorder: "#504945",
          sidebarRing: "#d3869b",
          radius: "0.25rem",
        },
      },
    },
  },
  // --- Solarized Dark ---
  {
    id: "solarized",
    name: "Solarized",
    description: "Solarized dark base03",
    variants: {
      light: {
        colors: {
          background: "#fdf6e3",
          foreground: "#002b36",
          card: "#f5efdb",
          cardForeground: "#002b36",
          popover: "#f5efdb",
          popoverForeground: "#002b36",
          primary: "#268bd2",
          primaryForeground: "#fdf6e3",
          secondary: "#eee8d5",
          secondaryForeground: "#657b83",
          muted: "#eee8d5",
          mutedForeground: "#839496",
          accent: "#eee8d5",
          accentForeground: "#657b83",
          destructive: "#dc322f",
          border: "#ddd6c3",
          input: "#ddd6c3",
          ring: "#268bd2",
          sidebar: "#eee8d5",
          sidebarForeground: "#002b36",
          sidebarPrimary: "#268bd2",
          sidebarPrimaryForeground: "#fdf6e3",
          sidebarAccent: "#eee8d5",
          sidebarAccentForeground: "#657b83",
          sidebarBorder: "#ddd6c3",
          sidebarRing: "#268bd2",
          radius: "0.375rem",
        },
      },
      dark: {
        colors: {
          background: "#002b36",
          foreground: "#fdf6e3",
          card: "#073642",
          cardForeground: "#fdf6e3",
          popover: "#073642",
          popoverForeground: "#fdf6e3",
          primary: "#268bd2",
          primaryForeground: "#002b36",
          secondary: "#073642",
          secondaryForeground: "#93a1a1",
          muted: "#073642",
          mutedForeground: "#586e75",
          accent: "#586e75",
          accentForeground: "#93a1a1",
          destructive: "#dc322f",
          border: "#073642",
          input: "#073642",
          ring: "#268bd2",
          sidebar: "#002128",
          sidebarForeground: "#fdf6e3",
          sidebarPrimary: "#268bd2",
          sidebarPrimaryForeground: "#002b36",
          sidebarAccent: "#586e75",
          sidebarAccentForeground: "#93a1a1",
          sidebarBorder: "#073642",
          sidebarRing: "#268bd2",
          radius: "0.375rem",
        },
      },
    },
  },
  // --- Tokyo Night ---
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    description: "Deep navy with soft pastels",
    variants: {
      light: {
        colors: {
          background: "#e8e8e8",
          foreground: "#1a1b26",
          card: "#ffffff",
          cardForeground: "#1a1b26",
          popover: "#ffffff",
          popoverForeground: "#1a1b26",
          primary: "#7aa2f7",
          primaryForeground: "#1a1b26",
          secondary: "#d7d7d7",
          secondaryForeground: "#565f89",
          muted: "#d7d7d7",
          mutedForeground: "#565f89",
          accent: "#d7d7d7",
          accentForeground: "#565f89",
          destructive: "#f7768e",
          border: "#d7d7d7",
          input: "#d7d7d7",
          ring: "#7aa2f7",
          sidebar: "#f0f0f0",
          sidebarForeground: "#1a1b26",
          sidebarPrimary: "#7aa2f7",
          sidebarPrimaryForeground: "#1a1b26",
          sidebarAccent: "#d7d7d7",
          sidebarAccentForeground: "#565f89",
          sidebarBorder: "#d7d7d7",
          sidebarRing: "#7aa2f7",
          radius: "0.375rem",
        },
      },
      dark: {
        colors: {
          background: "#1a1b26",
          foreground: "#c0caf5",
          card: "#24283b",
          cardForeground: "#c0caf5",
          popover: "#24283b",
          popoverForeground: "#c0caf5",
          primary: "#7aa2f7",
          primaryForeground: "#1a1b26",
          secondary: "#292e42",
          secondaryForeground: "#a9b1d6",
          muted: "#292e42",
          mutedForeground: "#565f89",
          accent: "#414868",
          accentForeground: "#a9b1d6",
          destructive: "#f7768e",
          border: "#292e42",
          input: "#292e42",
          ring: "#7aa2f7",
          sidebar: "#16161e",
          sidebarForeground: "#c0caf5",
          sidebarPrimary: "#7aa2f7",
          sidebarPrimaryForeground: "#1a1b26",
          sidebarAccent: "#414868",
          sidebarAccentForeground: "#a9b1d6",
          sidebarBorder: "#292e42",
          sidebarRing: "#7aa2f7",
          radius: "0.375rem",
        },
      },
    },
  },
  // --- Catppuccin Mocha ---
  {
    id: "catppuccin",
    name: "Catppuccin",
    description: "Mocha flavor with soft pastels",
    variants: {
      light: {
        colors: {
          background: "#eff1f5",
          foreground: "#4c4f69",
          card: "#ffffff",
          cardForeground: "#4c4f69",
          popover: "#ffffff",
          popoverForeground: "#4c4f69",
          primary: "#8839ef",
          primaryForeground: "#ffffff",
          secondary: "#e6e9ef",
          secondaryForeground: "#5c5f77",
          muted: "#e6e9ef",
          mutedForeground: "#6c6f85",
          accent: "#e6e9ef",
          accentForeground: "#5c5f77",
          destructive: "#d20f39",
          border: "#bcc0cc",
          input: "#bcc0cc",
          ring: "#8839ef",
          sidebar: "#e4e7ec",
          sidebarForeground: "#4c4f69",
          sidebarPrimary: "#8839ef",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#e6e9ef",
          sidebarAccentForeground: "#5c5f77",
          sidebarBorder: "#bcc0cc",
          sidebarRing: "#8839ef",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#1e1e2e",
          foreground: "#cdd6f4",
          card: "#313244",
          cardForeground: "#cdd6f4",
          popover: "#313244",
          popoverForeground: "#cdd6f4",
          primary: "#cba6f7",
          primaryForeground: "#1e1e2e",
          secondary: "#45475a",
          secondaryForeground: "#bac2de",
          muted: "#45475a",
          mutedForeground: "#6c7086",
          accent: "#45475a",
          accentForeground: "#bac2de",
          destructive: "#f38ba8",
          border: "#45475a",
          input: "#45475a",
          ring: "#cba6f7",
          sidebar: "#181825",
          sidebarForeground: "#cdd6f4",
          sidebarPrimary: "#cba6f7",
          sidebarPrimaryForeground: "#1e1e2e",
          sidebarAccent: "#45475a",
          sidebarAccentForeground: "#bac2de",
          sidebarBorder: "#45475a",
          sidebarRing: "#cba6f7",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Rosé Pine ---
  {
    id: "rose-pine",
    name: "Rosé Pine",
    description: "Muted earthy pastel palette",
    variants: {
      light: {
        colors: {
          background: "#faf4f2",
          foreground: "#19171c",
          card: "#ffffff",
          cardForeground: "#19171c",
          popover: "#ffffff",
          popoverForeground: "#19171c",
          primary: "#cb7399",
          primaryForeground: "#ffffff",
          secondary: "#edebf1",
          secondaryForeground: "#6e6a86",
          muted: "#edebf1",
          mutedForeground: "#7a757f",
          accent: "#edebf1",
          accentForeground: "#6e6a86",
          destructive: "#e07a75",
          border: "#ddd8e4",
          input: "#ddd8e4",
          ring: "#cb7399",
          sidebar: "#f2edf1",
          sidebarForeground: "#19171c",
          sidebarPrimary: "#cb7399",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#edebf1",
          sidebarAccentForeground: "#6e6a86",
          sidebarBorder: "#ddd8e4",
          sidebarRing: "#cb7399",
          radius: "0.5rem",
        },
      },
      dark: {
        colors: {
          background: "#19171c",
          foreground: "#e0def4",
          card: "#242230",
          cardForeground: "#e0def4",
          popover: "#242230",
          popoverForeground: "#e0def4",
          primary: "#c4b5fd",
          primaryForeground: "#19171c",
          secondary: "#2a2733",
          secondaryForeground: "#b3a2ff",
          muted: "#2a2733",
          mutedForeground: "#6e6a86",
          accent: "#312e3d",
          accentForeground: "#b3a2ff",
          destructive: "#f28f8b",
          border: "#312e3d",
          input: "#312e3d",
          ring: "#c4b5fd",
          sidebar: "#141218",
          sidebarForeground: "#e0def4",
          sidebarPrimary: "#c4b5fd",
          sidebarPrimaryForeground: "#19171c",
          sidebarAccent: "#312e3d",
          sidebarAccentForeground: "#b3a2ff",
          sidebarBorder: "#312e3d",
          sidebarRing: "#c4b5fd",
          radius: "0.5rem",
        },
      },
    },
  },
  // --- Midnight ---
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep navy minimal dark theme",
    variants: {
      light: {
        colors: {
          background: "#f5f7fa",
          foreground: "#1a1d23",
          card: "#ffffff",
          cardForeground: "#1a1d23",
          popover: "#ffffff",
          popoverForeground: "#1a1d23",
          primary: "#4a6fa5",
          primaryForeground: "#ffffff",
          secondary: "#e2e8f0",
          secondaryForeground: "#475569",
          muted: "#e2e8f0",
          mutedForeground: "#64748b",
          accent: "#dbeafe",
          accentForeground: "#1e40af",
          destructive: "#dc2626",
          border: "#cbd5e1",
          input: "#cbd5e1",
          ring: "#4a6fa5",
          sidebar: "#f1f5f9",
          sidebarForeground: "#1a1d23",
          sidebarPrimary: "#4a6fa5",
          sidebarPrimaryForeground: "#ffffff",
          sidebarAccent: "#dbeafe",
          sidebarAccentForeground: "#1e40af",
          sidebarBorder: "#cbd5e1",
          sidebarRing: "#4a6fa5",
          radius: "0.375rem",
        },
      },
      dark: {
        colors: {
          background: "#1a1d23",
          foreground: "#e2e8f0",
          card: "#242830",
          cardForeground: "#e2e8f0",
          popover: "#242830",
          popoverForeground: "#e2e8f0",
          primary: "#6b8fd4",
          primaryForeground: "#1a1d23",
          secondary: "#2e333d",
          secondaryForeground: "#94a3b8",
          muted: "#2e333d",
          mutedForeground: "#64748b",
          accent: "#1e3a5f",
          accentForeground: "#dbeafe",
          destructive: "#f87171",
          border: "#2e333d",
          input: "#2e333d",
          ring: "#6b8fd4",
          sidebar: "#14161c",
          sidebarForeground: "#e2e8f0",
          sidebarPrimary: "#6b8fd4",
          sidebarPrimaryForeground: "#1a1d23",
          sidebarAccent: "#1e3a5f",
          sidebarAccentForeground: "#dbeafe",
          sidebarBorder: "#2e333d",
          sidebarRing: "#6b8fd4",
          radius: "0.375rem",
        },
      },
    },
  },
];

/** Returns all built-in themes. */
export function listBuiltinThemes(): Theme[] {
  return BUILTIN_THEMES;
}

/** Look up a theme by ID, returning undefined if not found. */
export function getBuiltinTheme(id: string): Theme | undefined {
  return BUILTIN_THEMES.find((t) => t.id === id);
}

/** Returns the default theme (the first built-in). */
export function getDefaultTheme(): Theme {
  return BUILTIN_THEMES[0] ?? BUILTIN_THEMES.find((t) => t.id === DEFAULT_THEME_ID) ?? BUILTIN_THEMES[0]!;
}
