// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Artifact describes the file to download for a Release on the running platform.
 */
export class Artifact {
    /**
     * Creates a new Artifact instance.
     * @param {Partial<Artifact>} [$$source = {}] - The source object to create the Artifact.
     */
    constructor($$source = {}) {
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["filetype"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["platform"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["arch"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Artifact}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact(/** @type {Partial<Artifact>} */($$parsedSource));
    }
}

/**
 * Release is what a Provider returns from Check when there is something newer.
 */
export class Release {
    /**
     * Creates a new Release instance.
     * @param {Partial<Release>} [$$source = {}] - The source object to create the Release.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["channel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["publishedAt"] = undefined;
        }
        if (!("artifact" in $$source)) {
            /**
             * @member
             * @type {Artifact}
             */
            this["artifact"] = (new Artifact());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Verification | null | undefined}
             */
            this["verification"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["metadata"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Provider is set by the Updater after Check; provider implementations
             * should leave it empty. Used to route a follow-up Download back to the
             * same source.
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Release}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField5_0($$parsedSource["artifact"]);
        }
        if ("verification" in $$parsedSource) {
            $$parsedSource["verification"] = $$createField6_0($$parsedSource["verification"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new Release(/** @type {Partial<Release>} */($$parsedSource));
    }
}

/**
 * Verification carries everything the Updater needs to authenticate the
 * downloaded bytes. A Provider populates this from the release source; the
 * Updater verifies against it using its configured trust root.
 * 
 * Either Digest+DigestAlgo, Signature+SignatureAlgo, or both may be present.
 * When both are present, both are checked; either failing fails the update.
 * 
 * Signature verification always uses Config.PublicKey as the trust root. The
 * release source has no say in which key authenticates it — that is the entire
 * point of pinning a key out-of-band at build time. Releases that ship a
 * Signature without a configured Config.PublicKey fail closed.
 */
export class Verification {
    /**
     * Creates a new Verification instance.
     * @param {Partial<Verification>} [$$source = {}] - The source object to create the Verification.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * "sha256", "sha512"
             * @member
             * @type {string | undefined}
             */
            this["digestAlgo"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * raw digest bytes
             * @member
             * @type {string | undefined}
             */
            this["digest"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "ed25519", "ed25519ph", "ecdsa-p256"
             * @member
             * @type {string | undefined}
             */
            this["signatureAlgo"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * raw signature bytes
             * @member
             * @type {string | undefined}
             */
            this["signature"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verification instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Verification}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField3_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("digest" in $$parsedSource) {
            $$parsedSource["digest"] = $$createField1_0($$parsedSource["digest"]);
        }
        if ("signature" in $$parsedSource) {
            $$parsedSource["signature"] = $$createField3_0($$parsedSource["signature"]);
        }
        return new Verification(/** @type {Partial<Verification>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Artifact.createFrom;
const $$createType1 = Verification.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
