// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Artifact describes the file to download for a Release on the running platform.
 */
export class Artifact {
    "filename": string;
    "filetype"?: string;
    "size"?: number;
    "platform"?: string;
    "arch"?: string;

    /** Creates a new Artifact instance. */
    constructor($$source: Partial<Artifact> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Artifact instance from a string or object.
     */
    static createFrom($$source: any = {}): Artifact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Artifact($$parsedSource as Partial<Artifact>);
    }
}

/**
 * Release is what a Provider returns from Check when there is something newer.
 */
export class Release {
    "version": string;
    "channel"?: string;
    "name"?: string;
    "notes"?: string;
    "publishedAt"?: Date;
    "artifact": Artifact;
    "verification"?: Verification | null;
    "metadata"?: { [_ in string]?: any };

    /**
     * Provider is set by the Updater after Check; provider implementations
     * should leave it empty. Used to route a follow-up Download back to the
     * same source.
     */
    "provider"?: string;

    /** Creates a new Release instance. */
    constructor($$source: Partial<Release> = {}) {
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("artifact" in $$source)) {
            this["artifact"] = (new Artifact());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     */
    static createFrom($$source: any = {}): Release {
        const $$createField4_0 = $Create.DateFromTime;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("publishedAt" in $$parsedSource) {
            $$parsedSource["publishedAt"] = $$createField4_0($$parsedSource["publishedAt"]);
        }
        if ("artifact" in $$parsedSource) {
            $$parsedSource["artifact"] = $$createField5_0($$parsedSource["artifact"]);
        }
        if ("verification" in $$parsedSource) {
            $$parsedSource["verification"] = $$createField6_0($$parsedSource["verification"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new Release($$parsedSource as Partial<Release>);
    }
}

/**
 * Verification carries everything the Updater needs to authenticate the
 * downloaded bytes. A Provider populates this from the release source; the
 * Updater verifies against it using its configured trust root.
 * 
 * Either Digest+DigestAlgo, Signature+SignatureAlgo, or both may be present.
 * When both are present, both are checked; either failing fails the update.
 * 
 * Signature verification always uses Config.PublicKey as the trust root. The
 * release source has no say in which key authenticates it — that is the entire
 * point of pinning a key out-of-band at build time. Releases that ship a
 * Signature without a configured Config.PublicKey fail closed.
 */
export class Verification {
    /**
     * "sha256", "sha512"
     */
    "digestAlgo"?: string;

    /**
     * raw digest bytes
     */
    "digest"?: string;

    /**
     * "ed25519", "ed25519ph", "ecdsa-p256"
     */
    "signatureAlgo"?: string;

    /**
     * raw signature bytes
     */
    "signature"?: string;

    /** Creates a new Verification instance. */
    constructor($$source: Partial<Verification> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Verification instance from a string or object.
     */
    static createFrom($$source: any = {}): Verification {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField3_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("digest" in $$parsedSource) {
            $$parsedSource["digest"] = $$createField1_0($$parsedSource["digest"]);
        }
        if ("signature" in $$parsedSource) {
            $$parsedSource["signature"] = $$createField3_0($$parsedSource["signature"]);
        }
        return new Verification($$parsedSource as Partial<Verification>);
    }
}

// Private type creation functions
const $$createType0 = Artifact.createFrom;
const $$createType1 = Verification.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
